### ISSUE TITLE
Timeout uploading large competition bundles locally

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#1286]
```
Traceback (most recent call last):
  File "/home/azureuser/deploy/codalab/apps/jobs/models.py", line 221, in run_job_task
    result = computation(job)
  File "/home/azureuser/deploy/codalab/apps/web/tasks.py", line 94, in create_it
    competition = competition_def.unpack()
  File "/home/azureuser/.virtualenvs/venv/local/lib/python2.7/site-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)
  File "/home/azureuser/deploy/codalab/apps/web/models.py", line 1363, in unpack
    phase.input_data.save(phase_input_data_file(phase), File(io.BytesIO(zf.read(phase_spec['input_data']))))
  File "/home/azureuser/.virtualenvs/venv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 86, in save
    self.name = self.storage.save(name, content)
  File "/home/azureuser/.virtualenvs/venv/local/lib/python2.7/site-packages/django/core/files/storage.py", line 48, in save
    name = self._save(name, content)
  File "/home/azureuser/deploy/codalab/codalab/azure_storage.py", line 86, in _save
    f.write(data)
  File "/home/azureuser/deploy/codalab/codalab/azure_storage.py", line 181, in write
    self.connection.put_block(self.container, self.name, data, blockid)
  File "/home/azureuser/.virtualenvs/venv/local/lib/python2.7/site-packages/azure/storage/blobservice.py", line 748, in put_block
    response = self._perform_request(request)
  File "/home/azureuser/.virtualenvs/venv/local/lib/python2.7/site-packages/azure/storage/storageclient.py", line 143, in _perform_request
    resp = self._filter(request)
  File "/home/azureuser/.virtualenvs/venv/local/lib/python2.7/site-packages/azure/storage/storageclient.py", line 132, in _perform_request_worker
    return self._httpclient.perform_request(request)
  File "/home/azureuser/.virtualenvs/venv/local/lib/python2.7/site-packages/azure/http/httpclient.py", line 144, in perform_request
    self.send_request_headers(connection, request.headers)
  File "/home/azureuser/.virtualenvs/venv/local/lib/python2.7/site-packages/azure/http/httpclient.py", line 125, in send_request_headers
    connection.endheaders()
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1178, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
```

**Comment by percyliang** [comment]
Can you say more?

**Comment by ckcollab** [comment]
I added a stacktrace above, uploading the AutoML competition is giving me this error (manual upload of competition + datasets as opposed to using OrganizerDataSet reference UUIDs).

Got the fail locally and on codalabtest now, looking into it... may be a decent time to try/upgrade new Azure module.

**Comment by percyliang** [comment]
Ah, 'competition bundles' clarifies it.
