### ISSUE TITLE
Uncaught broken pipe error when user connection drops

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-competitions#1398]
When I refresh a page many times, the browser presumably closes old sockets mid-response, which leads to this error on the server:
```
[12/Nov/2015 11:43:44] "GET /worksheets/0x026f9e00792943c1b16e199444091cd2/ HTTP/1.1" 200 10597
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 197, in send_preamble
    self._write('Server: %s\r\n' % self.server_software)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[12/Nov/2015 11:43:44] "GET /worksheets/0x026f9e00792943c1b16e199444091cd2/ HTTP/1.1" 500 59
```

Doesn't cause any problems besides extra log errors, but it would be good to catch/handle it.

**Comment by FlavioAlexander** [comment]
Opened on worksheets https://github.com/codalab/codalab-worksheets/issues/24
