### ISSUE TITLE
CodaLab fails to install

### ISSUE THREAD

**Issue by abmnv** [codalab/codalab-competitions#1430]
Installing a fresh version of CodaLab on Azure VM results the following error:
```
Command /home/azureuser/codalab/venv/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-b8tMkO/Pillow/setup.py';exec(comp
ile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Fpl36B-record/insta
ll-record.txt --single-version-externally-managed --compile --install-headers /home/azureuser/codalab/venv/include/site/python2.7 failed with
 error code 1 in /tmp/pip-build-b8tMkO/Pillow
Exception information:
Traceback (most recent call last):
  File "/home/azureuser/codalab/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/azureuser/codalab/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 309, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/home/azureuser/codalab/venv/local/lib/python2.7/site-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/home/azureuser/codalab/venv/local/lib/python2.7/site-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/home/azureuser/codalab/venv/local/lib/python2.7/site-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /home/azureuser/codalab/venv/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-b8tMkO/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Fpl36B-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/azureuser/codalab/venv/include/site/python2.7 failed with error code 1 in /tmp/pip-build-b8tMkO/Pillow

Traceback (most recent call last):
  File "/home/azureuser/codalab/venv/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/azureuser/codalab/venv/local/lib/python2.7/site-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/home/azureuser/codalab/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 53: ordinal not in range(128)
ERROR: Failed to install requirements: /home/azureuser/codalab/codalab/requirements/dev_azure_nix.txt
azureuser@cbibop:~/codalab$ less /home/azureuser/codalab/codalab/requirements/dev_azure_nix.txt
-r common.txt
supervisor==3.0
uWSGI==1.9.16
pycrypto==2.6
MySQL-python
# Use sckoo@stanford.edu's patched argcomplete, until pull request has been accepted
# https://github.com/kislyuk/argcomplete/pull/118
git+https://github.com/kashizui/argcomplete.git@allow-overridden-subparsersaction
```
Thanks.

**Comment by cash** [comment]
This stack trace is not long enough to contain the issue in the install process. My issue was not having libjpeg installed so Pillow would not install.  This github issue should be closed.

Same partial stack trace:

```
ValueError: --enable-jpeg requested but jpeg not found, aborting.

----------------------------------------
Cleaning up...
  Removing temporary dir /home/apluser/codalab/venv/build...
Command /home/apluser/codalab/venv/bin/python2.7 -c "import setuptools, tokenize;__file__='/home/apluser/codalab/venv/build/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Vi3fFt-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/apluser/codalab/venv/include/site/python2.7 failed with error code 1 in /home/apluser/codalab/venv/build/Pillow
Exception information:
Traceback (most recent call last):
  File "/home/apluser/codalab/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/apluser/codalab/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/home/apluser/codalab/venv/local/lib/python2.7/site-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/home/apluser/codalab/venv/local/lib/python2.7/site-packages/pip/req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/home/apluser/codalab/venv/local/lib/python2.7/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /home/apluser/codalab/venv/bin/python2.7 -c "import setuptools, tokenize;__file__='/home/apluser/codalab/venv/build/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Vi3fFt-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/apluser/codalab/venv/include/site/python2.7 failed with error code 1 in /home/apluser/codalab/venv/build/Pillow

Traceback (most recent call last):
  File "/home/apluser/codalab/venv/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/apluser/codalab/venv/local/lib/python2.7/site-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/home/apluser/codalab/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 53: ordinal not in range(128)
ERROR: Failed to install requirements: /home/apluser/codalab/codalab/requirements/dev_azure_nix.txt

**Comment by FlavioAlexander** [comment]
@abmnv Were you able to install requirements?

**Comment by abmnv** [comment]
Yes, after installing libjpeg library with "apt-get install libjpeg-dev" the installation works fine. Thanks.
