### ISSUE TITLE
Fail to set up local instance

### ISSUE THREAD

**Issue by ChengshuLi** [codalab/codalab-competitions#1509]
Hello,

Thanks in advance for reading this. 

I was trying to set up my local instance and followed the instruction from this page. 
https://github.com/codalab/codalab-competitions/wiki/Setup-Local-Worksheets

I finished installing all the requirements (except I had trouble downloading uWSGI==1.9.16 as it has some bugs for Mac OS 10.10, so I instead downloaded a different (newest stable) version uWSGI==2.0.12)

I did not do anything for ~/.codalab/config.json. My default content is the following: does it seem right?
```
{
  2     "aliases": {
  3         "localhost": "http://localhost:2800",
  4         "main": "https://worksheets.codalab.org/bundleservice"
  5     },
  6     "cli": {
  7         "default_address": "https://worksheets.codalab.org/bundleservice",
  8         "verbose": 1
  9     },
 10     "server": {
 11         "auth": {
 12             "class": "MockAuthHandler"
 13         },
 14         "class": "SQLiteModel",
 15         "engine_url": "sqlite:////Users/apple/.codalab/bundle.db",
 16         "host": "localhost",
 17         "port": 2800,
 18         "verbose": 1
 19     },
 20     "workers": {
 21         "q": {
 22             "dispatch_command": "python $CODALAB_CLI/scripts/dispatch-q.py",
 23             "verbose": 1
 24         }
```

Then I was stuck when I tried to run this:

```
cd $HOME/codalab/codalab-worksheets
./manage syncdb --migrate
./manage config_gen
./manage set_site your_domain_name.com
```

Here is my error:
```
$ ./manage syncdb --migrate
./config/templates/startup_env.sh: line 2: length: command not found
./config/templates/startup_env.sh: line 2: {%: command not found
./config/templates/startup_env.sh: line 4: {%: command not found
./config/templates/startup_env.sh: line 6: {%: command not found
./config/templates/startup_env.sh: line 7: {%: command not found
./config/templates/startup_env.sh: line 8: export: `{{e}}={{v}}': not a valid identifier
./config/templates/startup_env.sh: line 9: {%: command not found
Usage: manage.py subcommand [options] [args]

Options:
  -v VERBOSITY, --verbosity=VERBOSITY
                        Verbosity level; 0=minimal output, 1=normal output,
                        2=verbose output, 3=very verbose output
  --settings=SETTINGS   The Python path to a settings module, e.g.
                        "myproject.settings.main". If this isn't provided, the
                        DJANGO_SETTINGS_MODULE environment variable will be
                        used.
  --pythonpath=PYTHONPATH
                        A directory to add to the Python path, e.g.
                        "/home/djangoprojects/myproject".
  --traceback           Print traceback on exception
  --configuration=CONFIGURATION
                        The name of the configuration class to load, e.g.
                        "Development". If this isn't provided, the
                        DJANGO_CONFIGURATION environment variable will be
                        used.
  --version             show program's version number and exit
  -h, --help            show this help message and exit
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/apple/Desktop/codalab-worksheets/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "/Users/apple/Desktop/codalab-worksheets/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 376, in execute
    sys.stdout.write(self.main_help_text() + '\n')
  File "/Users/apple/Desktop/codalab-worksheets/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 242, in main_help_text
    for name, app in six.iteritems(get_commands()):
  File "/Users/apple/Desktop/codalab-worksheets/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 109, in get_commands
    apps = settings.INSTALLED_APPS
  File "/Users/apple/Desktop/codalab-worksheets/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/Users/apple/Desktop/codalab-worksheets/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/apple/Desktop/codalab-worksheets/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 132, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/apple/Desktop/codalab-worksheets/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  3         "localhost": "http://localhost:2800",
  File "/Users/apple/Desktop/codalab-worksheets/venv/lib/python2.7/site-packages/configurations/importer.py", line 127, in load_module
    mod = imp.load_module(fullname, *self.location)
  File "/Users/apple/Desktop/codalab-worksheets/codalab/codalab/settings/__init__.py", line 14, in <module>
    class Base(Settings):
  File "/Users/apple/Desktop/codalab-worksheets/codalab/codalab/settings/__init__.py", line 20, in Base
    config = json.loads(open(config_path).read())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

My environment is Python 2.7.8 and Mac OS 10.10.5

Any help is greatly appreciated! Thanks! 

-Eric

**Comment by percyliang** [comment]
Please close this ticket and re-open it on codalab/codalab-worksheets.

Also, do a git pull on codalab-worksheets/master to get some updates I just
pushed.
