### ISSUE TITLE
Error during submission to VQA challenge.

### ISSUE THREAD

**Issue by ajabri** [codalab/codalab-competitions#1563]
Error after status changed to 'submitted'. Log:

```
Traceback (most recent call last):
  File "/home/azureuser/codalab/codalab/codalabtools/compute/worker.py", line 255, in run
    shutil.rmtree(file_path)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/codalabtemp/tmpAquRkx/run'
```

**Comment by FlavioAlexander** [comment]
@ajabri Thanks for the report, I will let you know once a fix is in place.

**Comment by kelkalot** [comment]
I have the same error for another challenge that I try to setup:

Traceback (most recent call last):
  File "/home/azureuser/codalab/codalab/codalabtools/compute/worker.py", line 255, in run
    shutil.rmtree(file_path)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/codalabtemp/tmpS6fi4J/run'

**Comment by FlavioAlexander** [comment]
@kelkalot Please try now, let me know if you run into the same issue again.

**Comment by FlavioAlexander** [comment]
Solved
