### ISSUE TITLE
Shutil bug?

### ISSUE THREAD

**Issue by kelkalot** [codalab/codalab-competitions#1565]
I get the following error when running my evaluation script on codalab (a local version work perfectly fine)

Traceback (most recent call last):
  File "/home/azureuser/codalab/codalab/codalabtools/compute/worker.py", line 255, in run
    shutil.rmtree(file_path)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/codalabtemp/tmpS6fi4J/run'

**Comment by FlavioAlexander** [comment]
@kelkalot Try again, let me know if you keep running into the same issue

**Comment by FlavioAlexander** [comment]
Solved
