### ISSUE TITLE
Populate script do not work

### ISSUE THREAD

**Issue by lsenta** [codalab/codalab-competitions#1600]
The documentation says:

Optional: Populate the site with some sample data.

```
python scripts/users.py
python scripts/competitions.py
```

users.py does not exist and competitions.py gives:

```
› python scripts/competitions.py  
/Users/laurent/.virtualenvs/codalab/lib/python2.7/site-packages/django_extensions/db/fields/__init__.py:425: DeprecationWarning: Django 1.8 features a native UUIDField, this UUIDField will be removed after Django 1.7 becomes unsupported.
  warnings.warn("Django 1.8 features a native UUIDField, this UUIDField will be removed after Django 1.7 becomes unsupported.", DeprecationWarning)

Traceback (most recent call last):
  File "scripts/competitions.py", line 39, in <module>
    guest1 = User.objects.get(username="guest1")
  File "/Users/laurent/.virtualenvs/codalab/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/laurent/.virtualenvs/codalab/lib/python2.7/site-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
apps.authenz.models.DoesNotExist: ClUser matching query does not exist.
```

**Comment by FlavioAlexander** [comment]
@lsenta It seems like `users.py` does not exist anymore. Then, we either deprecate this feature, or we add the missing module. Not really sure if competitions.py ever worked, feel free to play around with it and make modifications

**Comment by FlavioAlexander** [comment]
Replaced by management commands
