### ISSUE TITLE
Several and different errors when submitting

### ISSUE THREAD

**Issue by gautier-marti** [codalab/codalab-competitions#1607]
I try to create a competition, it seemed to work fine, but when I try to submit an answer.zip containing a file answer.txt to test it, the submission fails: it displays several and different error messages for the same file submitted successively.

For example, I get :

```
Traceback (most recent call last):
  File "/home/azureuser/codalab/codalab/codalabtools/compute/worker.py", line 348, in run
    env=os.environ
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

or 

```
Traceback (most recent call last):
  File "/home/azureuser/codalab/codalab/codalabtools/compute/worker.py", line 348, in run
    env=os.environ
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

or
```
Traceback (most recent call last):
  File "/home/azureuser/codalab/codalab/codalabtools/compute/worker.py", line 255, in run
    shutil.rmtree(file_path)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/codalabtemp/tmpo3gREj/run'
```

To be sure that it was not my scoring program which was buggy, I replaced it with an "example" scoring program, and get same error messages. Here is the scoring program:

```
#!/usr/bin/env python
import sys
import os
import os.path

input_dir = sys.argv[1]
output_dir = sys.argv[2]

submit_dir = os.path.join(input_dir, 'res')
truth_dir = os.path.join(input_dir, 'ref')

if not os.path.isdir(submit_dir):
    print "%s doesn't exist" % submit_dir

if os.path.isdir(submit_dir) and os.path.isdir(truth_dir):
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    output_filename = os.path.join(output_dir, 'scores.txt')
    output_file = open(output_filename, 'wb')

    truth_file = os.path.join(truth_dir, "answer.txt")
    truth = open(truth_file).read()

    submission_answer_file = os.path.join(submit_dir, "answer.txt")
    submission_answer = open(submission_answer_file).read()

    if truth == submission_answer:
        output_file.write("Difference:1")
    else:
        output_file.write("Difference:0")

    output_file.close()
```

**Comment by FlavioAlexander** [comment]
@gautier-marti  I will look into`OSError: [Errno 39] Directory not empty: '/codalabtemp/tmpo3gREj/run`. It seems like the temporary directory being use to process submission does not have the proper permissions. I haven't seen the other two errors before, so I would have to spend more time with them? Did you use our sample competitions, if yes. Which one? I might have to re-create the competition myself.

**Comment by gautier-marti** [comment]
Yes, I have just uploaded compute_pi as a competition bundle. It built correctly. Then I tried to submit answer.zip containing answer.txt containing 3.1415359, it is "Submitting", then I get the following error:

```
Traceback (most recent call last):
  File "/home/azureuser/codalab/codalab/codalabtools/compute/worker.py", line 348, in run
    env=os.environ
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Hope it helps. I will also try other competition bundles.

**Comment by FlavioAlexander** [comment]
@gautier-marti Probably something is wrong with `compute_pi` I haven't tried the bundle before. However, it seems like you got `Hello_World` working which is good I think. You don't need to upload the bundle again if a submission fails.  The `permission denied` comes once in a while, still tracking down the reason, but if you submit again it will work. Now, when you get a `submitting` status, you just need to wait, sometimes there are other submissions ahead in the queue, until they run you won't be able to run yours.

**Comment by julsal** [comment]
Hi Guys, I found one important point that might generate problems, although I can't say it is the reason for those listed here. The instruction below is present in compute/worker.py

`prog_cmd = prog_cmd.replace("python", join(run_dir, "/home/azureuser/anaconda/bin/python"))`

if someone decides to include `python` in the name of the py file...

**Comment by jponttuset** [comment]
Hi!
Any advances on this front?

I keep getting these errors constantly:
```
Traceback (most recent call last):
  File "/home/azureuser/codalab-competitions/codalab/codalabtools/compute/worker.py", line 291, in run
    shutil.rmtree(file_path)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/codalabtemp/tmpcFxAlU/run'
```
and
```
Traceback (most recent call last):
  File "/home/azureuser/codalab-competitions/codalab/codalabtools/compute/worker.py", line 384, in run
    env=os.environ
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
With the exact same file that worked at some point...

**Comment by ckcollab** [comment]
@jponttuset which server was this on, competition test or production? Thanks!

**Comment by jponttuset** [comment]
This was on the production server. I don't get them anymore, they were gone after some days.

**Comment by huskyjo** [comment]
I am having the same issue when making submission to competition

`Traceback (most recent call last):
  File "/home/azureuser/codalab-competitions/codalab/codalabtools/compute/worker.py", line 384, in run
    env=os.environ
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

Any ideas why?
