### ISSUE TITLE
Upload Sample Competition 

### ISSUE THREAD

**Issue by PatrickChrist** [codalab/codalab-competitions#1620]
Hey Everyone,

i am planning to host a segmentation challenge at CodaLab.

I tried to create and upload a new challenge by using a sample competition.
https://github.com/Tivix/competition-examples
None of the sample competition did work for me even the pi example.
I got the following error message while uploading.
```
Traceback (most recent call last):
  File "/home/azureuser/codalab-competitions/codalab/apps/jobs/models.py", line 234, in run_job_task
    result = computation(job)
  File "/home/azureuser/codalab-competitions/codalab/apps/web/tasks.py", line 98, in create_it
    competition = competition_def.unpack()
  File "/home/azureuser/codalab-competitions/venv/local/lib/python2.7/site-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)
  File "/home/azureuser/codalab-competitions/codalab/apps/web/models.py", line 1423, in unpack
    comp.image.save(comp_base['image'], File(io.BytesIO(zf.read(comp_base['image']))))
  File "/usr/lib/python2.7/zipfile.py", line 935, in read
    return self.open(name, "r", pwd).read()
  File "/usr/lib/python2.7/zipfile.py", line 961, in open
    zinfo = self.getinfo(name)
  File "/usr/lib/python2.7/zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'logo.jpg' in the archive"
```
Although logo.jgp is in the archive. Removing logo.jpg from the competition.yaml raises the same error and complaining about missing html files which are also present.

Thanks for your help,
Patrick

**Comment by FlavioAlexander** [comment]
Hello Patrick,
 
How did you zip the file? It seems like the bundle is not being zipped properly. For instance, try using something like:  zip -j name_of_zipe_file.zip file_to_be_zip. The -j flag will not create extra directories within the zip bundle.

Please let me know if that helps.

Best,

Flavio

**Comment by PatrickChrist** [comment]
Hey @FlavioAlexander 
Thanks for your help. That worked. I tried before with MacOS and Win7 GUI. You should add this to the WIKI! Thanks alot.
Patrick

**Comment by FlavioAlexander** [comment]
@PatrickChrist  my pleasure. I agree with you, I will add this to the wiki. Thanks a lot for the recommendation.
