### ISSUE TITLE
Cannot create new competition

### ISSUE THREAD

**Issue by devanshujain919** [codalab/codalab-competitions#1725]
Hi,

I am trying to upload a sample competition and it is giving me error as following:

```
Traceback (most recent call last):
  File "/home/azureuser/codalab-competitions/codalab/apps/jobs/models.py", line 234, in run_job_task
    result = computation(job)
  File "/home/azureuser/codalab-competitions/codalab/apps/web/tasks.py", line 98, in create_it
    competition = competition_def.unpack()
  File "/home/azureuser/codalab-competitions/venv/local/lib/python2.7/site-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)
  File "/home/azureuser/codalab-competitions/codalab/apps/web/models.py", line 1425, in unpack
    comp.image.save(comp_base['image'], File(io.BytesIO(zf.read(comp_base['image']))))
  File "/usr/lib/python2.7/zipfile.py", line 935, in read
    return self.open(name, "r", pwd).read()
  File "/usr/lib/python2.7/zipfile.py", line 961, in open
    zinfo = self.getinfo(name)
  File "/usr/lib/python2.7/zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'logo.jpg' in the archive"
```

However, the archive does contain these files. I am attaching the definition [here](https://www.dropbox.com/s/k4tvo0rtvnolc57/scisumm-competition.zip?dl=0) for reference. Any help is appreciated.

**Comment by ckcollab** [comment]
Actually, if you unzip that there is an extra folder, so your files are actually at `./scisumm-competition/logo.jpg` not `./logo.jpg`

So you need to re-zip just the files, not a "parent folder" :)

**Comment by devanshujain919** [comment]
Oh okay
Thanks
