### ISSUE TITLE
Cannot upload submission

### ISSUE THREAD

**Issue by devanshujain919** [codalab/codalab-competitions#1726]
Hi,

I am trying to run a sample competition. I tried to make a submission, but I got this error:

```
Traceback (most recent call last):
  File "/home/azureuser/codalab-competitions/codalab/codalabtools/compute/worker.py", line 384, in run
    env=os.environ
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
Can someone help me understand the reason for this ?

**Comment by devanshujain919** [comment]
Nevermind
