### ISSUE TITLE
Submission bug

### ISSUE THREAD

**Issue by felipebravom** [codalab/codalab-competitions#1729]
Please find below the stack trace of a submission made to a competition I'm co-organizing.
Any ideas of what is happening?
Cheers,
Felipe

Traceback (most recent call last):
  File "/home/azureuser/codalab-competitions/codalab/codalabtools/compute/worker.py", line 307, in run
    bundles = getBundle(root_dir, blob_service, container, run_id, 'run')
  File "/home/azureuser/codalab-competitions/codalab/codalabtools/compute/worker.py", line 186, in getBundle
    return getThem(bundle_id, bundle_rel_path, {}, 0)
  File "/home/azureuser/codalab-competitions/codalab/codalabtools/compute/worker.py", line 182, in getThem
    getThem(v, join(bundle_rel_path, k), bundles, depth + 1)
  File "/home/azureuser/codalab-competitions/codalab/codalabtools/compute/worker.py", line 182, in getThem
    getThem(v, join(bundle_rel_path, k), bundles, depth + 1)
  File "/home/azureuser/codalab-competitions/codalab/codalabtools/compute/worker.py", line 182, in getThem
    getThem(v, join(bundle_rel_path, k), bundles, depth + 1)
  File "/home/azureuser/codalab-competitions/codalab/codalabtools/compute/worker.py", line 134, in getThem
    blob = blob_service.get_blob(container, bundle_id)
  File "/home/azureuser/codalab-competitions/venv/local/lib/python2.7/site-packages/azure/storage/blobservice.py", line 1722, in get_blob
    response = self._perform_request(request, None)
  File "/home/azureuser/codalab-competitions/venv/local/lib/python2.7/site-packages/azure/storage/storageclient.py", line 172, in _perform_request
    resp = self._filter(request)
  File "/home/azureuser/codalab-competitions/venv/local/lib/python2.7/site-packages/azure/storage/storageclient.py", line 161, in _perform_request_worker
    return self._httpclient.perform_request(request)
  File "/home/azureuser/codalab-competitions/venv/local/lib/python2.7/site-packages/azure/http/httpclient.py", line 218, in perform_request
    self.send_request_headers(connection, request.headers)
  File "/home/azureuser/codalab-competitions/venv/local/lib/python2.7/site-packages/azure/http/httpclient.py", line 197, in send_request_headers
    connection.endheaders()
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1216, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused

**Comment by ckcollab** [comment]
Where was this submission pushed to, production (codalab.org) or the test site? We've been having quite a few problems with Azure lately but will hopefully be fixed soon thanks to some work @FlavioAlexander is doing!

**Comment by felipebravom** [comment]
It was pushed to the production site. Thanks for the prompt reply!
