### ISSUE TITLE
Docker-stage non-functional

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1770]
http://docker-server.lri.fr/ 

- Currently cannot create a competition

- Currently cannot create worker queues

- Admin customization page leads to 'site unavailable upon submission

**Comment by ckcollab** [comment]
Please move this to the other issue, let's keep things together in this milestone & relevant issue: https://github.com/codalab/codalab-competitions/issues/1748

**Comment by ckcollab** [comment]
> Admin customization page leads to 'site unavailable upon submission

So the only time this happened was when Competition wasn't set, fixed now.

**Comment by ckcollab** [comment]
Current problems:
- [ ] Local SSL not working
- [ ] Docker staging server can't connect via pyrabbit.........?


```
# Rabbit directly requested seems to work
>>> requests.get("http://rabbit:20001").content
'<!doctype html>\n<meta http-equiv="X-UA-Compatible" content="IE=edge" />\n<html>\n  <head>\n    <title>RabbitMQ Management</title>\n    <script src="js/ejs.min.js" type="text/javascript"></script>\n    <script src="js/jquery-1.6.4.min.js" type="text/javascript"></script>\n    <script src="js/jquery.flot.min.js" type="text/javascript"></script>\n    <script src="js/jquery.flot.time.min.js" type="text/javascript"></script>\n    <script src="js/sammy.min.js" type="text/javascript"></script>\n    <script src="js/json2.js" type="text/javascript"></script>\n    <script src="js/base64.js" type="text/javascript"></script>\n    <script src="js/global.js" type="text/javascript"></script>\n    <script src="js/main.js" type="text/javascript"></script>\n    <script src="js/prefs.js" type="text/javascript"></script>\n    <script src="js/help.js" type="text/javascript"></script>\n    <script src="js/formatters.js" type="text/javascript"></script>\n    <script src="js/charts.js" type="text/javascript"></script>\n\n    <link href="css/main.css" rel="stylesheet" type="text/css"/>\n    <link href="favicon.ico" rel="shortcut icon" type="image/x-icon"/>\n\n<!--[if lte IE 8]>\n    <script src="js/excanvas.min.js" type="text/javascript"></script>\n    <link href="css/evil.css" rel="stylesheet" type="text/css"/>\n<![endif]-->\n  </head>\n  <body>\n    <div id="outer"></div>\n    <div id="debug"></div>\n    <div id="scratch"></div>\n  </body>\n</html>\n'


# No SSL certificate set
>>> bool(settings.SSL_CERTIFICATE)
False


# And then pyrabbit gets 404...?
>>> from pyrabbit.api import Client
>>> rabbit = Client("rabbit:20001", settings.RABBITMQ_DEFAULT_USER, settings.RABBITMQ_DEFAULT_PASS)
>>> rabbit.get_users()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pyrabbit/api.py", line 190, in get_users
    users = self._call(Client.urls['all_users'], 'GET')
  File "/usr/local/lib/python2.7/site-packages/pyrabbit/api.py", line 108, in _call
    resp = self.http.do_call(path, method, body, headers)
  File "/usr/local/lib/python2.7/site-packages/pyrabbit/http.py", line 102, in do_call
    raise HTTPError(content, resp.status_code, resp.text, path, body)
HTTPError: 404 - Not found. (None) (users) (None)
```

**Comment by ckcollab** [comment]
Fixed being unable to connect to rabbit.... endpoint missing `/api/` somehow..

**Comment by dragonlocke** [comment]
Case Closed
