### ISSUE TITLE
YAML Error in Submission metadata

### ISSUE THREAD

**Issue by braingineer** [codalab/codalab-competitions#1819]
Hello,

I am helping organize a competition and we are having issues in submission. The error is:

```
Traceback (most recent call last):
  File "/home/azureuser/codalab-competitions/codalab/codalabtools/compute/worker.py", line 307, in run
    bundles = getBundle(root_dir, blob_service, container, run_id, 'run')
  File "/home/azureuser/codalab-competitions/codalab/codalabtools/compute/worker.py", line 186, in getBundle
    return getThem(bundle_id, bundle_rel_path, {}, 0)
  File "/home/azureuser/codalab-competitions/codalab/codalabtools/compute/worker.py", line 182, in getThem
    getThem(v, join(bundle_rel_path, k), bundles, depth + 1)
  File "/home/azureuser/codalab-competitions/codalab/codalabtools/compute/worker.py", line 182, in getThem
    getThem(v, join(bundle_rel_path, k), bundles, depth + 1)
  File "/home/azureuser/codalab-competitions/codalab/codalabtools/compute/worker.py", line 173, in getThem
    bundle_info = yaml.load(mf)
  File "/home/azureuser/codalab-competitions/venv/local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/home/azureuser/codalab-competitions/venv/local/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/home/azureuser/codalab-competitions/venv/local/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/azureuser/codalab-competitions/venv/local/lib/python2.7/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/home/azureuser/codalab-competitions/venv/local/lib/python2.7/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/home/azureuser/codalab-competitions/venv/local/lib/python2.7/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/home/azureuser/codalab-competitions/venv/local/lib/python2.7/site-packages/yaml/scanner.py", line 128, in peek_token
    self.fetch_more_tokens()
  File "/home/azureuser/codalab-competitions/venv/local/lib/python2.7/site-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/home/azureuser/codalab-competitions/venv/local/lib/python2.7/site-packages/yaml/scanner.py", line 580, in fetch_value
    self.get_mark())
ScannerError: mapping values are not allowed here
  in "/codalabtemp/tmpXdQ_z3/run/input/ref/metadata", line 14, column 31
```

Isn't this metadata that's automatically generated upon submission? Or is there anything that we are doing to cause this issue? 

Thanks
Brian

**Comment by ckcollab** [comment]
It looks like you're sending over some invalid data?

> ScannerError: mapping values are not allowed here

https://stackoverflow.com/questions/9055371/python-and-pyaml-yaml-scanner-scannererror-mapping-values-are-not-allowed-her

**Comment by braingineer** [comment]
The user is not the one who creates this yaml file:

https://github.com/codalab/codalab-competitions/blob/a6e0f1b39173ddd2f70d578bc87f8bd08fb239dc/codalab/apps/web/tasks.py#L410

**Comment by ckcollab** [comment]
I don't think so, those generate `run` files and such, not `metadata` from my memory? Could be wrong! I would check the input data, reference data, scoring program, submission, etc. and make sure all of the metadata files are formatted properly.

**Comment by braingineer** [comment]
Thanks @ckcollab --- I'm coming into the project a little late to help debug, but from what I could gather only the web interface was used to setup the parameters of the competition.  The other metadata file is on the scorer, but that metadata file is only 2 lines long and the above error is pointing to line 14.

The second link above points to some code that looks like it runs when a file is submission for evaluation.  Or am I reading that wrong? 

Otherwise, I'm not sure which metadata it's referring to.  Upon submitting to the competition, I only uploaded a zip file and filled out the form. There was no other metadata file required, right? Or should there have been metadata in the zipped submission?

**Comment by ckcollab** [comment]
> The second link above points to some code that looks like it runs when a file is submitted for evaluation. Or am I reading that wrong?

Yes, that's correct, it prepares some metadata files for the compute worker to consume.

> Otherwise, I'm not sure which metadata it's referring to. 

I would look through your competition input data, reference data, etc. -- there could be a bug somewhere, but it's probably just a badly formatted YAML file somewhere in there.

**Comment by braingineer** [comment]
I don't think that we've uploaded any yaml files. Please correct me if wrong so I can hunt down this issue :). 

Where our interaction with yaml comes in:

- We filled out the competition information page. This auto generates a yaml file for the competition
- We uploaded a scorer, which includes a metadata file that is 2 lines long is loaded with yaml
- We have the "per_submission_metadata" checked, so each submission for each user generates metadata that is parsed with yaml

The errors all point to it to being a yaml file, right?  So it has to be one of these three possibilities?

**Comment by ckcollab** [comment]
> I don't think that we've uploaded any yaml files.

The competition should have some? In the scoring program, for example.

`in "/codalabtemp/tmpXdQ_z3/run/input/ref/metadata", line 14, column 31`

Looks like it's in your reference data, potentially?

**Comment by braingineer** [comment]
It can't be --- the reference data metadata is only 2 lines.   Could codalab be adding to it?

**Comment by braingineer** [comment]
Hi @ckcollab 

So, we figured out the reason on our end. It turns out the reference file needed to be named something specific that we had incorrect.   I guess it was the expectation of the scorer for this file name that was breaking things. (though, the error message is still bizarrely mysterious.. maybe there is a way to make that more informative?)

Thanks for your time, I super appreciate it.  :).

**Comment by ckcollab** [comment]
It's always something silly! I created a new ticket for a better error message or some kind of qol improvement: #1820

If you could add more specifics there we can probably improve this experience, thanks :)
