### ISSUE TITLE
Test Codalab Competitions: Drills various issues encountered

### ISSUE THREAD

**Issue by Tthomas63** [codalab/codalab-competitions#1879]
Documenting any weird/unusual errors/bugs from the Drills Isabelle sent us.

- [x] Bad Header error: There seems to be a score column header ( Or some related variable ) with a newline in it. Causes the following error.

```
django            | 2017-07-27 18:14:40,646 ERROR Internal Server Error: /competitions/1491/results/3742/data
django            | Traceback (most recent call last):
django            |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
django            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
django            |     return self.dispatch(request, *args, **kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
django            |     return handler(request, *args, **kwargs)
django            |   File "/app/codalab/apps/web/views.py", line 812, in get
django            |     response["Content-Disposition"] = "attachment; filename=%s results.csv" % phase.competition.title
django            |   File "/usr/local/lib/python2.7/site-packages/django/http/response.py", line 179, in __setitem__
django            |     value = self._convert_to_charset(value, 'latin-1', mime_encode=True)
django            |   File "/usr/local/lib/python2.7/site-packages/django/http/response.py", line 174, in _convert_to_charset
django            |     raise BadHeaderError("Header values can't contain newlines (got %r)" % value)
django            | BadHeaderError: Header values can't contain newlines (got '=?utf-8?q?attachment=3B_filename=3D=E2=80=9CTyler=E2=80=99s_Test_Comp?=\n =?utf-8?b?4oCcIHJlc3VsdHMuY3N2?=')
```

- [ ] Combined Datasets not recognizing nested files. Might have something to do with URI keys between the file in the combined dataset, and the standalone file in datasets being different.
```ada-130001ff-14c5-464b-b2f6-57addb739c5a```
vs
```Ada    4a55f4c9-7cde-41f8-b649-e5eeb92731ed```
Error traceback:
```
Traceback (most recent call last):
  File "/app/codalab/codalabtools/compute/worker.py", line 373, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/app/codalab/codalabtools/compute/worker.py", line 149, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/app/codalab/codalabtools/compute/worker.py", line 149, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/app/codalab/codalabtools/compute/worker.py", line 106, in get_bundle
    urllib.urlretrieve(url, bundle_file.name)
  File "/opt/conda/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/opt/conda/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/opt/conda/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/opt/conda/lib/python2.7/urllib.py", line 469, in open_file
    return self.open_local_file(url)
  File "/opt/conda/lib/python2.7/urllib.py", line 483, in open_local_file
    raise IOError(e.errno, e.strerror, e.filename)
IOError: [Errno 2] No such file or directory: 'dataset_data_file/ada-130001ff-14c5-464b-b2f6-57addb739c5a.zip'
```
- [x] Deleting competitions results in 404. ( Deleting does not work )
Error:
```
postgres          | STATEMENT:  DELETE FROM "web_submissionscoredef" WHERE "id" IN (4392)
django            | 2017-07-27 18:35:43,716 ERROR Internal Server Error: /competitions/delete_competition/1490
django            | Traceback (most recent call last):
django            |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
django            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
django            |     return self.dispatch(request, *args, **kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
django            |     return bound_func(*args, **kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
django            |     return view_func(request, *args, **kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
django            |     return func(self, *args2, **kwargs2)
django            |   File "/app/codalab/apps/web/views.py", line 131, in dispatch
django            |     return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
django            |     return handler(request, *args, **kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 257, in post
django            |     return self.delete(request, *args, **kwargs)
django            |   File "/app/codalab/apps/web/views.py", line 377, in delete
django            |     self.object.delete()
django            |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 695, in delete
django            |     collector.delete()
django            |   File "/usr/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 277, in delete
django            |     query.delete_batch(pk_list, self.using)
django            |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 49, in delete_batch
django            |     self.do_query(self.get_meta().db_table, where, using=using)
django            |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 34, in do_query
django            |     self.get_compiler(using).execute_sql(None)
django            |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
django            |     cursor.execute(sql, params)
django            |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
django            |     return super(CursorDebugWrapper, self).execute(sql, params)
django            |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
django            |     return self.cursor.execute(sql, params)
django            |   File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
django            |     six.reraise(dj_exc_type, dj_exc_value, traceback)
django            |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
django            |     return self.cursor.execute(sql, params)
django            | IntegrityError: update or delete on table "web_submissionscoredef" violates foreign key constraint "scoredef_id_refs_id_2d8c837a" on table "web_submissionscoreset"
django            | DETAIL:  Key (id)=(4392) is still referenced from table "web_submissionscoreset".
```

**Comment by Tthomas63** [comment]
Was able to fix 2 issues. The only issue left related to drills is the nested datasets issue.

**Comment by ckcollab** [comment]
Can we make a new issues just for nested datasets -- or is that fixed? (was that the div problem?)
