### ISSUE TITLE
Questions about configuration of Azure

### ISSUE THREAD

**Issue by anbangleo** [codalab/codalab-competitions#1910]
Dear sir/madam,
  Sorry to trouble you but I still have a question which afflicts me all day.
  When I try to configure azure-service-bus, could you please tell me what the "account_key" is? Which means what's the difference between the "SBS_ACCOUNT_KEY" and "SBS_SHARED_ACCESS_KEY_VALUE"? 
  I found the wiki was out of date such as the Azure doesn't have the "connection information" button in the bottom of the Service Bus Page.
  Thank you very much.

Best Regards.

**Comment by ckcollab** [comment]
I believe you need to make a classic service bus? You can also try the newer setup, using docker. Checkout the documentation here:
http://codalab-competitions.readthedocs.io/en/latest/

Make sure you checkout the develop branch :)

**Comment by anbangleo** [comment]
I am very very happy to receive your reply!
Very glad to know your solution,
but I still have two questions:
1)in".env" the database part, I noticed the name is "codalab_website" but in Wiki the database we created was "MySQL_DevDB", and in your newest submission the database engine changed to postgres. So how to configure the Database part of ".env"?
2) when I upload my competition bundles locally, it will show the error "There was an error uploading the file. Please try again." the browser told me "[Error] Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR) http://10.2.14.108:9090/api/competition/create/sas"
Meanwhile the control console showed as following:
_2017-08-30 11:05:30,916 ERROR Internal Server Error: /api/competition/create/sas
Traceback (most recent call last):
  File "/home/codalab-competitions/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/codalab-competitions/venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/codalab-competitions/venv/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/codalab-competitions/venv/local/lib/python2.7/site-packages/rest_framework/views.py", line 327, in dispatch
    response = self.handle_exception(exc)
  File "/home/codalab-competitions/venv/local/lib/python2.7/site-packages/rest_framework/views.py", line 324, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/codalab-competitions/codalab/apps/api/views/competition_views.py", line 67, in post
    response_data = _generate_blob_sas_url(prefix, '.zip')
  File "/home/codalab-competitions/codalab/apps/api/views/competition_views.py", line 51, in _generate_blob_sas_url
    duration=60)
  File "/home/codalab-competitions/codalab/codalab/azure_storage.py", line 224, in make_blob_sas_url
    sas_token = sas.generate_signed_query_string(resource_path, 'b', sap)
  File "/home/codalab-competitions/venv/local/lib/python2.7/site-packages/azure/storage/sharedaccesssignature.py", line 116, in generate_signed_query_string
    table_name,
  File "/home/codalab-competitions/venv/local/lib/python2.7/site-packages/azure/storage/sharedaccesssignature.py", line 158, in _generate_signed_query_dict
    content_type, table_name)
  File "/home/codalab-competitions/venv/local/lib/python2.7/site-packages/azure/storage/sharedaccesssignature.py", line 176, in _generate_signature
    canonicalized_resource = '/' + self.account_name + path
TypeError: cannot concatenate 'str' and 'NoneType' objects
[30/Aug/2017 11:05:30] "POST /api/competition/create/sas HTTP/1.1" 500 20182_
Could you please tell me how to solve with these problems?
Thank you very much

**Comment by ckcollab** [comment]
Ah, I just updated `.env_sample` with postgres stuff, if you do a `git pull` should get it. Here it is for reference as well.

```# Used engine (mysql, postgresql, sqlite3, memory)
DB_ENGINE=postgresql

# Connection parameters
DB_HOST=postgres
DB_PORT=5432
DB_NAME=codalab_website
DB_USER=root
DB_PASSWORD=password

# Path where DB files will be mapped
DB_DATA_PATH=./var/data/postgres```

**Comment by ckcollab** [comment]
Re: your other error, may need to setup CORS or some such properly? The setup guide is fairly fresh, so please let me know when you have fixes for these problems and where they would be good to add to the current docs.

Have a good one!

**Comment by anbangleo** [comment]
Dear friend, I have solved with these issues, it's not about the CORS but must use the port 8000. Because my port 8000 is occupied by other apps before, after change it it's ok. Thanks.
