### ISSUE TITLE
Delete competition not working

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2074]
![image](https://user-images.githubusercontent.com/7594063/33111553-923b7d4e-cf03-11e7-8067-01d6ab262b6c.png)

**Comment by ckcollab** [comment]
Exception information for this:

```django            | 2017-11-22 05:46:51,093 ERROR Internal Server Error: /competitions/delete_competition/1721
django            | Traceback (most recent call last):
django            |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
django            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
django            |     return self.dispatch(request, *args, **kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
django            |     return bound_func(*args, **kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
django            |     return view_func(request, *args, **kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
django            |     return func(self, *args2, **kwargs2)
django            |   File "/app/codalab/apps/web/views.py", line 139, in dispatch
django            |     return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
django            |     return handler(request, *args, **kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 257, in post
django            |     return self.delete(request, *args, **kwargs)
django            |   File "/app/codalab/apps/web/views.py", line 403, in delete
django            |     self.object.delete()
django            |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 695, in delete
django            |     collector.delete()
django            |   File "/usr/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 277, in delete
django            |     query.delete_batch(pk_list, self.using)
django            |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 49, in delete_batch
django            |     self.do_query(self.get_meta().db_table, where, using=using)
django            |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 34, in do_query
django            |     self.get_compiler(using).execute_sql(None)
django            |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
django            |     cursor.execute(sql, params)
django            |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
django            |     return self.cursor.execute(sql, params)
django            |   File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
django            |     six.reraise(dj_exc_type, dj_exc_value, traceback)
django            |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
django            |     return self.cursor.execute(sql, params)
django            | IntegrityError: update or delete on table "web_submissionscoredef" violates foreign key constraint "scoredef_id_refs_id_2d8c837a" on table "web_submissionscoreset"
django            | DETAIL:  Key (id)=(7761) is still referenced from table "web_submissionscoreset".
django            | 
```

**Comment by madclam** [comment]
I deleted a bunch of competitions. It seems to be working again.

**Comment by ckcollab** [comment]
I believe this is still broken, but just for certain competitions with strange leaderboard relations, for whatever reason. Will keep an eye on it.
