### ISSUE TITLE
 LiTS - Liver Tumor Segmentation Challenge: Submission Evaluation Error

### ISSUE THREAD

**Issue by mahendrakhened** [codalab/codalab-competitions#2130]
Consecutived submissions to leaderboard are getting failed.

Log1:
Traceback (most recent call last):
  File "/tmp/codalab/tmp1sklfe/run/program/evaluate.py", line 11, in 
    from helpers.calc_metric import (dice,
  File "/tmp/codalab/tmp1sklfe/run/program/helpers/calc_metric.py", line 1, in 
    from medpy import metric
ImportError: No module named medpy

Log2:
Traceback (most recent call last):
  File "/worker/worker.py", line 275, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 142, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 142, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 102, in get_bundle
    z.extractall(bundle_path)
  File "/usr/local/lib/python2.7/zipfile.py", line 1043, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/local/lib/python2.7/zipfile.py", line 1031, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/local/lib/python2.7/zipfile.py", line 1087, in _extract_member
    shutil.copyfileobj(source, target)
  File "/usr/local/lib/python2.7/shutil.py", line 52, in copyfileobj
    fdst.write(buf)
IOError: [Errno 28] No space left on device

**Comment by dantino** [comment]
+1 I got the same errors.

**Comment by ckcollab** [comment]
We will have to update the new servers to accommodate this, should be done in the next week or two.

**Comment by ckcollab** [comment]
...just kidding, the process is much much easier on the new servers, no messing with obscure Azure CLI commands to boost the size on these harddrives! Updated the legacy image as well. Seems to be chugging along now...

**Comment by XudongWang12Sigma** [comment]
I met the same error, don't know how to solve it.

Traceback (most recent call last):
  File "/worker/worker.py", line 313, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 133, in get_bundle
    z.extractall(bundle_path)
  File "/usr/local/lib/python2.7/zipfile.py", line 1040, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/local/lib/python2.7/zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/local/lib/python2.7/zipfile.py", line 1084, in _extract_member
    shutil.copyfileobj(source, target)
  File "/usr/local/lib/python2.7/shutil.py", line 66, in copyfileobj
    fdst.write(buf)
IOError: [Errno 28] No space left on device
