### ISSUE TITLE
CodaLab parsing error submission

### ISSUE THREAD

**Issue by Cyvhee** [codalab/codalab-competitions#2143]
Hi
When I upload a submission on CodaLab, it throws the following error: 

Traceback (most recent call last):
  File "/worker/worker.py", line 275, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 142, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 133, in get_bundle
    metadata = yaml.load(mf)
  File "/usr/local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/usr/local/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python2.7/site-packages/yaml/parser.py", line 174, in parse_document_start
    self.peek_token().start_mark)
ParserError: expected '', but found ''
  in "/tmp/codalab/tmpMNbxe3/run/program/metadata", line 3, column 3

Evaluating the submission on my local PC works fine, so I assume the issue is related to the internal processing of the files on CodaLab?

Are people experiencing the same issue and does anybody have an idea of what goes wrong?
Thanks in advance!

Cheers
Cynthia

**Comment by ckcollab** [comment]
```
ParserError: expected '', but found ''
in "/tmp/codalab/tmpMNbxe3/run/program/metadata", line 3, column 3```

Please make sure your metadata is properly formatted and such...?

**Comment by ckcollab** [comment]
Hey Cynthia, did this work for you? Hopefully just a simple formatting problem on the `metadata` file?

Thanks!

**Comment by Cyvhee** [comment]
Hi

That was indeed the problem ... stupid of me not to check this :-).
Many thanks!

Cynthia

**Comment by ckcollab** [comment]
No problem at all! Glad it works :)
