### ISSUE TITLE
Empty pages cause exception

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#2310]
![image](https://user-images.githubusercontent.com/2185159/41073225-2f671760-69b7-11e8-89ba-98b66a6e1833.png)

```
Traceback (most recent call last):

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
  response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
  return self.dispatch(request, *args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
  return bound_func(*args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
  return view_func(request, *args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
  return func(self, *args2, **kwargs2)
File "/app/codalab/apps/web/views.py", line 144, in dispatch
  return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
  return handler(request, *args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 154, in get
  context = self.get_context_data(**kwargs)
File "/app/codalab/apps/web/views.py", line 1369, in get_context_data
  context['submission_info_list'] = paginator.page(page)
File "/usr/local/lib/python2.7/site-packages/django/core/paginator.py", line 50, in page
  number = self.validate_number(number)
File "/usr/local/lib/python2.7/site-packages/django/core/paginator.py", line 43, in validate_number
  raise EmptyPage('That page contains no results')
EmptyPage: That page contains no results
```

**Comment by Tthomas63** [comment]
Will make sure we're grabbing defaults right, if so, catch this exception and throw a different status code (instead of 500)

**Comment by ckcollab** [comment]
NOTE: This already may be fixed?

**How to replicate and check this?**

**Comment by Tthomas63** [comment]
I believe we did fix this. The issue was when there was multiple phases with different amounts of pages, the pagination links would default to the first phase while still passing the page parameter even if it didn't exist.
