### ISSUE TITLE
Server Unstable Problem

### ISSUE THREAD

**Issue by whyou5945** [codalab/codalab-competitions#2387]
I'm trying to attend the CTW-Recognition competition, and evaluate my algorithm on the server. But i often got the following problem, got **FAILED** result...

It seems that the server is not very stable. It would be kind if you could fix it.
Thanks.

**Comment by whyou5945** [comment]
Traceback (most recent call last):
  File "/worker/worker.py", line 275, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 142, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 142, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 92, in get_bundle
    urllib.urlretrieve(url, bundle_file.name)
  File "/usr/local/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/local/lib/python2.7/urllib.py", line 273, in retrieve
    block = fp.read(bs)
  File "/usr/local/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/local/lib/python2.7/ssl.py", line 766, in recv
    return self.read(buflen)
  File "/usr/local/lib/python2.7/ssl.py", line 653, in read
    v = self._sslobj.read(len)
  File "/usr/local/lib/python2.7/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
SoftTimeLimitExceeded: SoftTimeLimitExceeded()

**Comment by whyou5945** [comment]
It seems that the server doesn't work well. The evaluation status stays **Submitted** for a day, what happened?

**Comment by ckcollab** [comment]
The CTW competition is using its own Queue and nothing is picking up the jobs. I don't believe it's a Codalab problem as the jobs are being passed to their own workers. Are you the competition organizer? Can you contact them to see?

**Comment by ckcollab** [comment]
@whyou5945 cool, let us know if there's anything we can do to help! Hopefully they just turned the workers off temporarily.
