### ISSUE TITLE
Scoring program failing

### ISSUE THREAD

**Issue by rajarsheem** [codalab/codalab-competitions#2419]
Hi,
I am running a competition:
https://competitions.codalab.org/competitions/18912 

When I am trying to submit, I am getting this error:
Traceback (most recent call last):
  File "/worker/worker.py", line 305, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 165, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 165, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 156, in get_bundle
    metadata = yaml.load(mf)
  File "/usr/local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 35, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/usr/local/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python2.7/site-packages/yaml/parser.py", line 143, in parse_implicit_document_start
    StreamEndToken):
  File "/usr/local/lib/python2.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python2.7/site-packages/yaml/scanner.py", line 257, in fetch_more_tokens
    % ch.encode('utf-8'), self.get_mark())
ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "/tmp/codalab/tmpmNHaMy/run/input/ref/metadata", line 1, column 8

Both my reference and submissions are TAB separated files. Please help.

**Comment by jmbanda** [comment]
So what was the solution for this issue? I have the same problem, but this was just closed.
