### ISSUE TITLE
Submission Failed due to `ValueError`

### ISSUE THREAD

**Issue by dasirra** [codalab/codalab-competitions#2461]
Hello,

I'm having troubles using the platform in my own AWS infrstructure. All is working fine until I upload a submission (this operation works perfectly in CodaLab). I'm getting this error:
```
worker_compute    | 2018-11-15 09:34:56,690 INFO Task is scoring.
worker_site       | 2018-11-15 09:34:56,712 INFO Changed submission status from submitting to submitted (id=2).
worker_site       | 2018-11-15 09:34:56,714 INFO It took: 0.535327 seconds to run
worker_compute    | docker system df requires API version 1.25, but the Docker daemon API version is 1.24
worker_compute    | [2018-11-15 09:34:56,727: ERROR/MainProcess] Task apps.web.tasks.compute_worker_run[37447a5a-78dc-454c-9710-66039cbde8e9] raised unexpected: ValueError('could not convert string to float: ',)
worker_compute    | Traceback (most recent call last):
worker_compute    |   File "/opt/conda/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
worker_compute    |     R = retval = fun(*args, **kwargs)
worker_compute    |   File "/opt/conda/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
worker_compute    |     return self.run(*args, **kwargs)
worker_compute    |   File "/app/codalab/apps/web/tasks.py", line 285, in compute_worker_run
worker_compute    |     run(data["id"], task_args)
worker_compute    |   File "/app/codalab/codalabtools/compute/worker.py", line 243, in run
worker_compute    |     docker_prune()
worker_compute    |   File "/app/codalab/codalabtools/compute/worker.py", line 73, in docker_prune
worker_compute    |     image_size = float(image_size[:-2])
worker_compute    | ValueError: could not convert string to float: 
```
Does anyone have the same problem?

**Comment by dasirra** [comment]
Solved. The problem was the API version of pre-installed docker on AMI. Just upgrade docker.
