### ISSUE TITLE
LiTS Sumission Error: IOError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by XudongWang12Sigma** [codalab/codalab-competitions#2513]
*** This is a template for an issue, please remove any non-relevant details to your issue ***
When I was submitting my results, the following error will appear:

Traceback (most recent call last):
  File "/worker/worker.py", line 313, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 133, in get_bundle
    z.extractall(bundle_path)
  File "/usr/local/lib/python2.7/zipfile.py", line 1040, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/local/lib/python2.7/zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/local/lib/python2.7/zipfile.py", line 1084, in _extract_member
    shutil.copyfileobj(source, target)
  File "/usr/local/lib/python2.7/shutil.py", line 66, in copyfileobj
    fdst.write(buf)
IOError: [Errno 28] No space left on device

Anyone has any solutions?

**Comment by ckcollab** [comment]
Please try again, I've cleared up some space on the workers..

We may want to re-enable our docker pruning feature soon @Tthomas63, made an issue for it #2514

**Comment by ckcollab** [comment]
Assuming things are fine now, closing issue
