### ISSUE TITLE
Failed submission

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2573]
https://autodl.lri.fr/competitions/115

Pytorch trials
Dataset 1
Submission 2722

Traceback (most recent call last):
  File "/worker/worker.py", line 653, in run
    ingestion_process.kill()
  File "/usr/lib/python2.7/subprocess.py", line 1572, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python2.7/subprocess.py", line 1562, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process

Resnet trails
Dataset 2
Submission 2735

Same error

This error is also found for other datasets of the same submission

**Comment by zhengying-liu** [comment]
Repeated issue:
https://github.com/codalab/codalab-competitions/issues/2577
