### ISSUE TITLE
Bad docker

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2574]
This issue concerns https://autodl.lri.fr/competitions/115/

The only baseline (other than baseline 0) which did tho fail is

Pavao | 2019-04-12 07:04 | 80bf4ee3d2fc | evariste/autodl | AutoDL-Test | 2661 | Finished

It was run as

Pavao | 2019-04-12 07:04 | 80bf4ee3d2fc | evariste/autodl | AutoDL-Test | 2661 | Finished | Scoring
with children processes:
2662, 2663, 2664, 2665, 2666 
All run an evariste/autodl | AutoDL-Test

[LinearPavao.pdf](https://github.com/codalab/codalab-competitions/files/3077099/LinearPavao.pdf)

**Comment by madclam** [comment]
In contrast, linear model submitted with a docker that takes advantage of GPUs (in principle) fails with various failure modes.

The submission that was closest to succeed is: 2817
All datasets except DATASET 2 terminated. The error for dataset 2 (2819) is:
```
Traceback (most recent call last):
  File "/worker/worker.py", line 653, in run
    ingestion_process.kill()
  File "/usr/lib/python2.7/subprocess.py", line 1572, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python2.7/subprocess.py", line 1562, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process
```

However, the learning curves for all processes that succeeded are pathological.
![1](https://user-images.githubusercontent.com/7594063/56090046-b8368280-5e9c-11e9-8651-43781c957b70.png)
![3](https://user-images.githubusercontent.com/7594063/56090047-b8368280-5e9c-11e9-9406-fcbdcab8755a.png)
![4](https://user-images.githubusercontent.com/7594063/56090048-b8368280-5e9c-11e9-9727-aad86bfb9e55.png)
![5](https://user-images.githubusercontent.com/7594063/56090049-b8cf1900-5e9c-11e9-85b8-f918f0f6e38c.png)

**Comment by madclam** [comment]
This should be fixed now, we have "good" dockers.
