### ISSUE TITLE
The CodaLab site is currently unavailable - spinning up own codalab instance

### ISSUE THREAD

**Issue by thomasyu888** [codalab/codalab-competitions#2729]
```
flower            | [E 191213 16:41:39 gen:661] Multiple exceptions in yield list
flower            |     Traceback (most recent call last):
flower            |       File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 656, in callback
flower            |         result_list.append(f.result())
flower            |       File "/usr/local/lib/python3.5/concurrent/futures/_base.py", line 398, in result
flower            |         return self.__get_result()
flower            |       File "/usr/local/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
flower            |         raise self._exception
flower            |       File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
flower            |         result = self.fn(*self.args, **self.kwargs)
flower            |       File "/usr/local/lib/python3.5/site-packages/celery/app/control.py", line 109, in conf
flower            |         return self._request('dump_conf', with_defaults=with_defaults)
flower            |       File "/usr/local/lib/python3.5/site-packages/celery/app/control.py", line 71, in _request
flower            |         timeout=self.timeout, reply=True,
flower            |       File "/usr/local/lib/python3.5/site-packages/celery/app/control.py", line 316, in broadcast
flower            |         limit, callback, channel=channel,
flower            |       File "/usr/local/lib/python3.5/site-packages/kombu/pidbox.py", line 283, in _broadcast
flower            |         chan = channel or self.connection.default_channel
flower            |       File "/usr/local/lib/python3.5/site-packages/kombu/connection.py", line 766, in default_channel
flower            |         self.connection
flower            |       File "/usr/local/lib/python3.5/site-packages/kombu/connection.py", line 751, in connection
flower            |         self._connection = self._establish_connection()
flower            |       File "/usr/local/lib/python3.5/site-packages/kombu/connection.py", line 706, in _establish_connection
flower            |         conn = self.transport.establish_connection()
flower            |       File "/usr/local/lib/python3.5/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
flower            |         conn = self.Connection(**opts)
flower            |       File "/usr/local/lib/python3.5/site-packages/amqp/connection.py", line 165, in __init__
flower            |         self.transport = self.Transport(host, connect_timeout, ssl)
flower            |       File "/usr/local/lib/python3.5/site-packages/amqp/connection.py", line 186, in Transport
flower            |         return create_transport(host, connect_timeout, ssl)
flower            |       File "/usr/local/lib/python3.5/site-packages/amqp/transport.py", line 299, in create_transport
flower            |         return TCPTransport(host, connect_timeout)
flower            |       File "/usr/local/lib/python3.5/site-packages/amqp/transport.py", line 95, in __init__
flower            |         raise socket.error(last_err)
flower            |     OSError: [Errno 111] Connection refused
```
What does this error mean?

**Comment by thomasyu888** [comment]
Ah, I had to change the `CODALAB_SITE_DOMAIN`... But now I'm getting another error:

```
...
django            | 2019-12-13 16:50:51,166 ERROR Internal Server Error: /
django            | Traceback (most recent call last):
django            |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
django            |     response = response.render()
django            |   File "/usr/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
django            |     self.content = self.rendered_content
django            |   File "/usr/local/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
django            |     context = self.resolve_context(self.context_data)
django            |   File "/usr/local/lib/python2.7/site-packages/django/template/response.py", line 159, in resolve_context
django            |     return RequestContext(self._request, context, current_app=self._current_app)
django            |   File "/usr/local/lib/python2.7/site-packages/debug_toolbar/panels/templates/panel.py", line 56, in _request_context___init__
django            |     context = processor(request)
django            |   File "/app/codalab/codalab/context_processors.py", line 24, in common_settings
django            |     'CHAHUB_URL': '//{}'.format(settings.CHAHUB_API_URL.split("//")[-1].split("/")[0].split('?')[0]),
django            | AttributeError: 'NoneType' object has no attribute 'split'`
``

**Comment by Didayolo** [comment]
Hi,

I've reported this issue here: #2724 

A solution is to un-comment some lines in `.env` file as following:
```
CHAHUB_API_URL=https://chahub.org/api/v1/
#CHAHUB_API_KEY=some-secret-key
SOCIAL_AUTH_CHAHUB_BASE_URL=https://chahub.org
```

**Comment by thomasyu888** [comment]
Works great!
