### ISSUE TITLE
verification error

### ISSUE THREAD

**Issue by SeoHyeong** [codalab/codalab-competitions#2742]
I've successfully installed codalab with python 3.6.8. However, whenever I try to login with `cl work`, it gives me the following error message. (codalab is the name of the virtual environment here)

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/client/json_api_client.py", line 15, in wrapper
    return f(*args, **kwargs)
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/client/json_api_client.py", line 414, in fetch
    query_params=self._pack_params(params),
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/worker/rest_client.py", line 62, in _make_request
    access_token = self._get_access_token()
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/lib/codalab_manager.py", line 426, in <lambda>
    lambda: self._authenticate(address, auth_handler),
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/lib/codalab_manager.py", line 496, in _authenticate
    token_info = auth_handler.generate_token('credentials', username, password)
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/server/auth.py", line 42, in generate_token
    {'grant_type': 'password', 'username': username, 'password': key}
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/server/auth.py", line 61, in _make_token_request
    response = urllib.request.urlopen(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/codalab/bin/cl", line 8, in <module>
    sys.exit(main())
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/bin/cl.py", line 10, in main
    cli.do_command(sys.argv[1:])
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/lib/bundle_cli.py", line 839, in do_command
    structured_result = command_fn()
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/lib/bundle_cli.py", line 833, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/lib/bundle_cli.py", line 2838, in do_work_command
    client, worksheet_uuid = self.parse_client_worksheet_uuid(args.worksheet_spec)
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/lib/bundle_cli.py", line 683, in parse_client_worksheet_uuid
    client, worksheet_uuid = self.manager.get_current_worksheet_uuid()
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/lib/codalab_manager.py", line 512, in get_current_worksheet_uuid
    worksheet_uuid = client.fetch_one('worksheets', params={'specs': '/'})['uuid']
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/client/json_api_client.py", line 424, in fetch_one
    results = self.fetch(resource_type, resource_id=resource_id, params=params)
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/client/json_api_client.py", line 49, in wrapper
    sys.exc_info()[2],
  File "/Users/user/codalab/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/client/json_api_client.py", line 15, in wrapper
    return f(*args, **kwargs)
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/client/json_api_client.py", line 414, in fetch
    query_params=self._pack_params(params),
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/worker/rest_client.py", line 62, in _make_request
    access_token = self._get_access_token()
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/lib/codalab_manager.py", line 426, in <lambda>
    lambda: self._authenticate(address, auth_handler),
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/lib/codalab_manager.py", line 496, in _authenticate
    token_info = auth_handler.generate_token('credentials', username, password)
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/server/auth.py", line 42, in generate_token
    {'grant_type': 'password', 'username': username, 'password': key}
  File "/Users/user/codalab/lib/python3.6/site-packages/codalab/server/auth.py", line 61, in _make_token_request
    response = urllib.request.urlopen(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
codalab.client.json_api_client.JsonApiException: Unable to fetch worksheets: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>
```

**Comment by Didayolo** [comment]
Hi,

I assume your are using the Codalab command line interface. If I'm wrong, please re-open this issue.

The Codalab CLI tool is related to [Codalab Worksheets](https://github.com/codalab/codalab-worksheets). 

It is a branch of the project separated from Codalab competitions (here). 
[Codalab competitions](https://competitions.codalab.org) is a platform hosting challenges while [Codalab worksheets](https://worksheets.codalab.org/) aims at running ML experiments on the cloud.

You can then raise your issue [here](https://github.com/codalab/codalab-worksheets/issues).
