### ISSUE TITLE
No space left on dev. Submission error. SemanticKITTI

### ISSUE THREAD

**Issue by Shathe** [codalab/codalab-competitions#2743]
Hi, 

I am having trouble evaluating my results in a competition.
The competition is SemanticKITTI: Semantic Segmentation.

I submit my results via the online web.
This is the error I get. It seems like some memory issues. I do not know who should I contact or what should I do:
```
Traceback (most recent call last):
  File "/worker/worker.py", line 313, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 133, in get_bundle
    z.extractall(bundle_path)
  File "/usr/local/lib/python2.7/zipfile.py", line 1040, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/local/lib/python2.7/zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/local/lib/python2.7/zipfile.py", line 1084, in _extract_member
    shutil.copyfileobj(source, target)
  File "/usr/local/lib/python2.7/shutil.py", line 66, in copyfileobj
    fdst.write(buf)
IOError: [Errno 28] No space left on dev
```

**Comment by jbehley** [comment]
The problem seems to happen since yesterday. 

Can I adjust or do something to solve the issue?

**Comment by Didayolo** [comment]
Hi,

It should be fixed now. Let me now if you still have an issue.

We have recently added new compute workers and a minor issue unmounted the storage on some of them. Sorry for the inconvenience.

**Comment by Didayolo** [comment]
I close the issue as it should be working. Please re-open it if you face any problem.

**Comment by jbehley** [comment]
Seems to work again. Thanks for your quick solution of the problem!
