### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by Didayolo** [codalab/codalab-competitions#2796]
* No logs when `metadata` file is missing.

**Comment by Didayolo** [comment]
* Absolutely no error message on a failed submission with time limit exceeded (nothing in the panel, nothing in ingestion error logs, nothing in scoring error logs, etc.). 

By looking at the compute worker logs we could find this 

```
[2020-06-22 23:31:52,703: ERROR/Worker-1] Run task timed out (task_id=667018).
Traceback (most recent call last):
  File "/worker/worker.py", line 667, in run
    time.sleep(1)
  File "/worker/worker.py", line 242, in alarm_handler
    raise ExecutionTimeLimitExceeded
ExecutionTimeLimitExceeded
[2020-06-22 23:31:52,703: INFO/Worker-1] Updating task=667018 status to failed
```

**Comment by Didayolo** [comment]
* Warn when submission contains subdirectory #2176

In this case the solution may be to handle the exceptions directly in the scoring program.

**Comment by Didayolo** [comment]
* Cryptic error message #2790
* Problem with computer workers running on AWS #2802

Many different issues result in the same, not explicit, error message. Something like:
```
File "/worker/worker.py", line 302, in run
    root_dir = tempfile.mkdtemp(dir=temp_dir)
  File "/usr/local/lib/python2.7/tempfile.py", line 339, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 2] No such file or directory: '/tmp/codalab/tmpTamW0S'  
```
or:
```
Traceback (most recent call last):
File "/worker/worker.py", line 313, in run
bundles = get_bundle(root_dir, 'run', bundle_url)
File "/worker/worker.py", line 173, in get_bundle
metadata[k] = get_bundle(bundle_path, k, v)
File "/worker/worker.py", line 136, in get_bundle
metadata_folder = _find_only_folder_with_metadata(bundle_path)
File "/worker/worker.py", line 44, in _find_only_folder_with_metadata
files_in_path = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/tmp/codalab/tmpdYCU7O/run/hidden_ref'
```
