### ISSUE TITLE
Code crashes in Mapillary Vistas Semantic Segmentation Task 

### ISSUE THREAD

**Issue by johnwlambert** [codalab/codalab-competitions#2822]
Hello Codalab,
I submitted an entry to the Mapillary Vistas Semantic Segmentation Task Robust Vision @ ECCV 2020, and I get the following "Failed" submission:

```
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/mnt/codalab/tmpsyH6FC/run/program/raster_eval.py", line 17, in evaluate_image_pair
    c = counts.reshape(shape).astype(np.int64)
ValueError: cannot reshape array of size 4226 into shape (65,65)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/mnt/codalab/tmpsyH6FC/run/program/raster_eval.py", line 17, in evaluate_image_pair
    c = counts.reshape(shape).astype(np.int64)
ValueError: cannot reshape array of size 4226 into shape (65,65)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/codalab/tmpsyH6FC/run/program/run.py", line 87, in 
    miou, iou = evaluate(gtDir, resDir)
  File "/mnt/codalab/tmpsyH6FC/run/program/raster_eval.py", line 35, in evaluate
    for i, result in enumerate(results):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 865, in next
    raise value
ValueError: cannot reshape array of size 4226 into shape (65,65)
```

It appears that an array of 4225 is expected instead of 4226. All of my input images are of the correct size and have indices in [0,65], as expected. Is this a competition codebase bug?

Thanks,
John

**Comment by Didayolo** [comment]
Hi,

Sorry for the late reply. It might be due to:
* Your submission (not the format required by the competition's code)
* The competition's code (a bug)

Only the competition organizers themselves can work this out. This repository is about the platform itself.

I close the issue because it's old. Feel free to re-open it if needed.
