### ISSUE TITLE
Error with submissions (no longer running): utf8' codec can't decode byte #x8b: invalid start byte

### ISSUE THREAD

**Issue by magrichard** [codalab/codalab-competitions#2859]
We are organizer of a competition that is supporting a benchmarking analysis currently under review for publication in a scientific journal (on going work with Isabelle Guyon on the HADACA project). 

Submissions that were previously working are not supported anymore by the system. When submitting, we get the following error message:

Traceback (most recent call last):
  File "/worker/worker.py", line 313, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 164, in get_bundle
    metadata = yaml.load(mf)
  File "/usr/local/lib/python2.7/site-packages/yaml/__init__.py", line 69, in load
    loader = Loader(stream)
  File "/usr/local/lib/python2.7/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python2.7/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/local/lib/python2.7/site-packages/yaml/reader.py", line 135, in determine_encoding
    self.update(1)
  File "/usr/local/lib/python2.7/site-packages/yaml/reader.py", line 165, in update
    exc.encoding, exc.reason)
ReaderError: 'utf8' codec can't decode byte #x8b: invalid start byte
  in "/tmp/codalab/tmpX18t8V/run/program/metadata", position 1

Here is the link of the competition: https://competitions.codalab.org/competitions/23660#learn_the_details

`eric2` and `tthomas63` have been added as admins to the competition

**Comment by Didayolo** [comment]
Hi Magali,

Are you still facing the issue?

**Comment by magrichard** [comment]
Hi, we reconstructed the competition from scratch and it worked. I don't know what was the issue!
