### ISSUE TITLE
IOError: [Errno 28] No space left on device on the LiTS competition site

### ISSUE THREAD

**Issue by zzangho** [codalab/codalab-competitions#2870]
![submission](https://user-images.githubusercontent.com/5129028/99934458-5e4cad00-2da1-11eb-9c8d-c598bf48eb1a.png)

I have tried to submit twenty result generated from same test code, but only three attempts was submitted successfully.
Other seventeen cases raised this error:

```
Traceback (most recent call last):
  File "/worker/worker.py", line 313, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 133, in get_bundle
    z.extractall(bundle_path)
  File "/usr/local/lib/python2.7/zipfile.py", line 1040, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/local/lib/python2.7/zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/local/lib/python2.7/zipfile.py", line 1084, in _extract_member
    shutil.copyfileobj(source, target)
  File "/usr/local/lib/python2.7/shutil.py", line 66, in copyfileobj
    fdst.write(buf)
IOError: [Errno 28] No space left on device
```

Could you advise me why this error happen?

My chrome version is Version 86.0.4240.198
The URL of the problem is [https://competitions.codalab.org/competitions/17094](https://competitions.codalab.org/competitions/17094)

**Comment by Didayolo** [comment]
Thank you for reporting this issue. It should be solved soon.

**Comment by Didayolo** [comment]
It should be resolved now. Feel free to re-open the issue if you face it again.
