### ISSUE TITLE
upload bundle failed: [Errno 0] Error

### ISSUE THREAD

**Issue by mxzf0213** [codalab/codalab-competitions#2918]
Hello, I am trying to deploy codalab locally. The website and data storage are both locally installed and with dockers. I use `minio` as the data storage but have problem when uploading the bundle. I ensure the data has been uploaded successfully, but some strange error (`[Errno 0] Error`) will appear, seems that the problem is caused when unpacking the bundle (The bundle is just compute-pi example download from [Example_compute_pi](https://github.com/codalab/codalab-competitions/wiki/Example_compute_pi))

Here is the worker site log:
```
 [2021-03-04 05:23:25,912: INFO/MainProcess] Received task: apps.web.tasks.create_competition[2106de72-d48f-48c4-baa2-458d75b1c355]

worker_site |

worker_site | -------------- celery@site-worker v3.1.26.post2 (Cipater)

worker_site | ---- **** -----

worker_site | --- * *** * -- Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-10.3

worker_site | -- * - **** ---

worker_site | - ** ---------- [config]

worker_site | - ** ---------- .> app: codalab:0x7f2c8c2a1450

worker_site | - ** ---------- .> transport: amqp://guest:**@rabbit:5672//

worker_site | - ** ---------- .> results: memcached://memcached:11211/

worker_site | - *** --- * --- .> concurrency: 16 (prefork)

worker_site | -- ******* ----

worker_site | --- ***** ----- [queues]

worker_site | -------------- .> site-worker exchange=site-worker(direct) key=site-worker

worker_site | .> submission-updates exchange=submission-updates(direct) key=submission-updates

worker_site |

worker_site | [tasks]

worker_site | . apps.newsletter.tasks.retry_mailing_list

worker_site | . apps.web.tasks.create_competition

worker_site | . apps.web.tasks.do_chahub_retries

worker_site | . apps.web.tasks.do_phase_migrations

worker_site | . apps.web.tasks.evaluate_submission

worker_site | . apps.web.tasks.make_modified_bundle

worker_site | . apps.web.tasks.re_run_all_submissions_in_phase

worker_site | . apps.web.tasks.send_chahub_general_stats

worker_site | . apps.web.tasks.send_chahub_updates

worker_site | . apps.web.tasks.send_mass_email

worker_site | . apps.web.tasks.update_submission

worker_site |

worker_site | 2021-03-04 05:23:25,915 INFO Creating competition for competition bundle (bundle_id=21)

worker_site | [2021-03-04 05:23:25,915: INFO/Worker-4] Creating competition for competition bundle (bundle_id=21)

worker_site | 2021-03-04 05:23:25,942 INFO CompetitionDefBundle::unpack begins (pk=21)

worker_site | [2021-03-04 05:23:25,942: INFO/Worker-4] CompetitionDefBundle::unpack begins (pk=21)

worker_site | [2021-03-04 05:23:25,943: INFO/Worker-4] CompetitionDefBundle::unpacking url=https://192.168.226.169:9000/private/uploads/competitions/e1cfd6f0-95a3-41f9-be82-4c5e308c8077/compute_pi_competition_bundle.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=123df826682cf4a589d4df27134618e21c4318b826fb8ea7115ee50f90083c0e&X-Amz-Date=20210304T052325Z&X-Amz-Credential=minioadmin%2F20210304%2Fus-east-1%2Fs3%2Faws4_request

worker_site | 2021-03-04 05:23:25,943 INFO CompetitionDefBundle::unpacking url=https://192.168.226.169:9000/private/uploads/competitions/e1cfd6f0-95a3-41f9-be82-4c5e308c8077/compute_pi_competition_bundle.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=123df826682cf4a589d4df27134618e21c4318b826fb8ea7115ee50f90083c0e&X-Amz-Date=20210304T052325Z&X-Amz-Credential=minioadmin%2F20210304%2Fus-east-1%2Fs3%2Faws4_request

worker_site | 2021-03-04 05:23:25,957 INFO CompetitionDefBundle::unpack creating base competition (pk=21)

worker_site | [2021-03-04 05:23:25,957: INFO/Worker-4] CompetitionDefBundle::unpack creating base competition (pk=21)

worker_site | 2021-03-04 05:23:25,979 INFO CompetitionDefBundle::unpack created base competition (pk=21)

worker_site | 2021-03-04 05:23:25,979 INFO CompetitionDefBundle::unpack attempting to save competition logo (pk=21)

worker_site | [2021-03-04 05:23:25,979: INFO/Worker-4] CompetitionDefBundle::unpack created base competition (pk=21)

worker_site | [2021-03-04 05:23:25,979: INFO/Worker-4] CompetitionDefBundle::unpack attempting to save competition logo (pk=21)

worker_site | 2021-03-04 05:25:00,973 INFO Completed update for job id=21. New status=3.

worker_site | [2021-03-04 05:25:00,973: INFO/Worker-4] Completed update for job id=21. New status=3.

worker_site | [2021-03-04 05:25:00,982: ERROR/Worker-4] Failed unpacking competition

worker_site | Traceback (most recent call last):

worker_site | File "/app/codalab/apps/web/tasks.py", line 126, in create_competition

worker_site | competition = competition_def.unpack()

worker_site | File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 431, in inner

worker_site | return func(*args, **kwargs)

worker_site | File "/app/codalab/apps/web/models.py", line 1801, in unpack

worker_site | comp.image.save(comp_base['image'], File(io.BytesIO(zf.read(comp_base['image']))))

worker_site | File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 86, in save

worker_site | self.name = self.storage.save(name, content)

worker_site | File "/usr/local/lib/python2.7/site-packages/storages/compat.py", line 19, in save

worker_site | return super(StorageMixin, self).save(name, content)

worker_site | File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 49, in save

worker_site | name = self._save(name, content)

worker_site | File "/usr/local/lib/python2.7/site-packages/storages/backends/s3boto.py", line 405, in _save

worker_site | key = self.bucket.get_key(encoded_name)

worker_site | File "/usr/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 193, in get_key

worker_site | key, resp = self._get_key_internal(key_name, headers, query_args_l)

worker_site | File "/usr/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 200, in _get_key_internal

worker_site | query_args=query_args)

worker_site | File "/usr/local/lib/python2.7/site-packages/boto/s3/connection.py", line 668, in make_request

worker_site | retry_handler=retry_handler

worker_site | File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request

worker_site | retry_handler=retry_handler)

worker_site | File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1030, in _mexe

worker_site | raise ex

worker_site | error: [Errno 0] Error

worker_site | [2021-03-04 05:25:01,000: INFO/MainProcess] Task apps.web.tasks.create_competition[2106de72-d48f-48c4-baa2-458d75b1c355] succeeded in 95.0856802s: None
```

**Comment by Didayolo** [comment]
Hi,

- Just to confirm: your local platform is up and running? You could create an user but when trying to upload a competition you have this error?

- On which github branch your Codalab instance is based?

**Comment by mxzf0213** [comment]
Yes, the platform is up and running well on my WSL. Create user is also okay. I git from the default page, which is ‘develop’ branch I think.

**Comment by bbearce** [comment]
If you have access to Azure Storage, I know how to make it work. I had trouble with minio and would be interested in seeing the resolution to this.

**Comment by mxzf0213** [comment]
Well, I will try Aws or Azure now, but I still want to deploy locally at last.

**Comment by mxzf0213** [comment]
@bbearce Thanks for recommending the Azure Storage. There is another problem. As I am trying to configure with Azure, I cannot find Connection Information button of Service Bus as the [guide](https://github.com/codalab/codalab-competitions/wiki/Storage#azure-blob-storage) describes. Maybe the view of panel is different than before, so I am not clear what does Default key of service bus actually means. Can you help me?

**Comment by bbearce** [comment]
So real quick are you using the develop branch of this project. That's the most stable from my point of view and with that one you don't need to configure that at all. All I do is:

* $ cp .env_sample .env
* Then I edit .env with my info. It's important to comment out the AWS and or minio section and use the azure section. All I need from azure are storage account name and key.
* Finally the CORS setting from that [link](https://github.com/codalab/codalab-competitions/wiki/Storage#azure-blob-storage) are needed. Namely the origins as * or you can be more specific and open up most if not all request methods (although I have a working deploy that didn't have request methods set, so that might not be true).

![image](https://user-images.githubusercontent.com/7649007/111701771-a9d40c80-8811-11eb-8057-b1b46841476a.png)

* If you haven't made then you will need to manually create containers public and bundles with bundles being private  and public being public or I think in azure it's called "blob" permissions.
![image](https://user-images.githubusercontent.com/7649007/111701839-c53f1780-8811-11eb-9dd2-3120a2210bf0.png)

**Comment by mxzf0213** [comment]
@bbearce Oh, it really worked. It's such a good and simple way to configure using Azure Storage! Thanks very muck!

**Comment by bbearce** [comment]
:) awesome
