### ISSUE TITLE
GPU-LRI-IDF queue bug (Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR)

### ISSUE THREAD

**Issue by SunHaozhe** [codalab/codalab-competitions#2956]
I observed a bug which is (presumably) linked to the GPU-LRI-IDF queue. Occasionally, I got the error `Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR` while submitting the same code. One example of the error log is shown below:

```
I0513 13:59:38.899394 140676528015168 scoring.py:186] Evaluating performance on episodes ... 
2021-05-13 13:59:43.032712: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-05-13 13:59:44.199499: E tensorflow/stream_executor/cuda/cuda_dnn.cc:328] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2021-05-13 13:59:44.200808: E tensorflow/stream_executor/cuda/cuda_dnn.cc:328] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/packages/metadl/metadl/core/scoring/scoring.py", line 226, in 
    app.run(scoring)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/app/packages/metadl/metadl/core/scoring/scoring.py", line 202, in scoring
    predictor = learner.fit(support_set)
  File "/tmp/codalab/tmp35S36u/run/input/res/code_dir/model.py", line 318, in fit
    projected_imgs = self.embedding_fn(image)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py", line 372, in call
    return super(Sequential, self).call(inputs, training=training, mask=mask)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py", line 386, in call
    inputs, training=training, mask=mask)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py", line 508, in _run_internal_graph
    outputs = node.layer(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/convolutional.py", line 247, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_ops.py", line 1018, in convolution_v2
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_ops.py", line 1148, in convolution_internal
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_ops.py", line 2592, in _conv2d_expanded_batch
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 938, in conv2d
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]
```

In order to reproduce this bug, 

1.  Go to the competition: [MetaDL (Omniglot)]( https://competitions.codalab.org/competitions/31431?secret_key=11cf0329-092e-42d8-9d35-290c20ecbadb). I have already added `pavao` and `tthomas63` as admins to this competition.
2. Repeatedly submit the same baseline solution `maml` or `proto` (found in the starting kit) to this competition more than 100 times.

According to my trials, this kind of bug (`Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR`) happens once every 40 or 50 submissions (of the same code) on average. 

This competition is a clone of a previous challenge [MetaDL](https://competitions.codalab.org/competitions/26638) with some minor changes and a new GPU queue. The submissions that I repeatedly submitted are the provided baseline code from the starting kit.

**Comment by Didayolo** [comment]
Thanks for reporting. I close the issue for now.
