### ISSUE TITLE
File not found error while uploading please help

### ISSUE THREAD

**Issue by Abhishekravindran** [codalab/codalab-competitions#2976]
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpda8GA4/run/program/evaluate.py", line 54, in 
    im = np.load(submission_answer_file)
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/codalab/tmpda8GA4/run/input/res/out_imgds.npy

**Comment by wulala-source** [comment]
Error:
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmp7aaMxa/run/program/eval_detection.py", line 283, in 
    area = eval(truth_dir,submit_dir)
  File "/tmp/codalab/tmp7aaMxa/run/program/eval_detection.py", line 253, in eval
    pred_vid_result  = json.load(open(osp.join(pred_dir, 'pred_vid_result.json')))
IOError: [Errno 2] No such file or directory: '/tmp/codalab/tmp7aaMxa/run/input/res/pred_vid_result.json'

**Comment by Didayolo** [comment]
I guess the fix was explained here: https://github.com/codalab/codalab-competitions/issues/2988

> "The zip file you upload containing a pred_part_result.json and a pred_vid_result.json should contain without any folder."
