### ISSUE TITLE
Error message in participant results tab

### ISSUE THREAD

**Issue by acletournel** [codalab/codalab-competitions#3001]
Error message is displayed in results tab for participants, but not for the organizer of the competition:
![ErrorResultsTabCodalab](https://user-images.githubusercontent.com/19392699/135111988-9f2c5cf3-d1d9-4695-955e-84842b87f4bc.png)

**Comment by dtuantran** [comment]
Here is the stack trace of django for the error :

django            | 2021-09-28 14:52:16,074 ERROR Internal Server Error: /competitions/19/results/35
django            | Traceback (most recent call last):
django            |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 41, in inner
django            |     response = get_response(request)
django            |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 217, in _get_response
django            |     response = self.process_exception_by_middleware(e, request)
django            |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 215, in _get_response
django            |     response = response.render()
django            |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 107, in render
django            |     self.content = self.rendered_content
django            |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 84, in rendered_content
django            |     content = template.render(context, self._request)
django            |   File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 64, in render
django            |     context = make_context(context, request, autoescape=self.backend.engine.autoescape)
django            |   File "/usr/local/lib/python3.8/site-packages/django/template/context.py", line 287, in make_context
django            |     raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
django            | TypeError: context must be a dict rather than HttpResponseForbidden.

**Comment by Didayolo** [comment]
As the organizer of this competition, the leaderboard is working well:

![org_screenshot](https://user-images.githubusercontent.com/11784999/135116929-f915e21d-edc8-4c0c-b9b9-ff8160b63861.png)

**Comment by Didayolo** [comment]
When I set another account as an admin of the competition, then it is able to see the leaderboard.

**Comment by Didayolo** [comment]
Fixed by Tyler.
