### ISSUE TITLE
Failed, competition phase is being migrated, please try again in a few minutes

### ISSUE THREAD

**Issue by aahmd9** [codalab/codalab-competitions#3064]
Hi, 

I am the organizer of the competition : https://codalab.lisn.upsaclay.fr/competitions/572 
When trying to submit a submission file, i get: Failed, competition phase is being migrated, please try again in a few minutes 

Could you please help me fix this?
Thanks!

Ali

**Comment by dtuantran** [comment]
Hello @aahmd9 ,
Have you retried the submission ? Can you tell the size of your submission file and how long it took to get the error ?

Bests,

**Comment by aahmd9** [comment]
Hi, 
I retired the submission, but still the same issue. 
The submission file is very small (arround  292 KB). 

Best,

**Comment by Didayolo** [comment]
Hi, 

Indeed I could reproduce the bug. It seems to happen only in your competition.

**Comment by Didayolo** [comment]
Maybe the problem comes from the settings of the competition?

Would you mind making me admin of the competition? My ID is `pavao`.

**Comment by Didayolo** [comment]
@dtuantran Not sure if it is related, but I've found this error in the logs:
```
postgres          | ERROR:  duplicate key value violates unique constraint "web_competitionsubmissio_submission_number_phase__8178a143_uniq"
postgres          | DETAIL:  Key (submission_number, phase_id, participant_id)=(12, 897, 1955) already exists.

```

**Comment by Didayolo** [comment]
Also, when trying to create a dump of the competition, it fails:

```python
worker_site       | 2021-12-14 18:32:00,146 INFO Creating Competion dump
worker_site       | [2021-12-14 18:32:00,146: INFO/ForkPoolWorker-233] Creating Competion dump
worker_site       | 2021-12-14 18:32:00,149 INFO Adding end-date
worker_site       | [2021-12-14 18:32:00,149: INFO/ForkPoolWorker-233] Adding end-date
worker_site       | 2021-12-14 18:32:00,158 INFO Adding HTML
worker_site       | [2021-12-14 18:32:00,158: INFO/ForkPoolWorker-233] Adding HTML
worker_site       | 2021-12-14 18:32:00,159 INFO Adding HTML
worker_site       | [2021-12-14 18:32:00,159: INFO/ForkPoolWorker-233] Adding HTML
worker_site       | 2021-12-14 18:32:00,160 INFO Adding HTML
worker_site       | [2021-12-14 18:32:00,160: INFO/ForkPoolWorker-233] Adding HTML
worker_site       | 2021-12-14 18:32:00,161 INFO Adding HTML
worker_site       | [2021-12-14 18:32:00,161: INFO/ForkPoolWorker-233] Adding HTML
worker_site       | 2021-12-14 18:32:00,162 INFO Adding HTML
worker_site       | [2021-12-14 18:32:00,162: INFO/ForkPoolWorker-233] Adding HTML
worker_site       | 2021-12-14 18:32:00,163 INFO Adding HTML
worker_site       | [2021-12-14 18:32:00,163: INFO/ForkPoolWorker-233] Adding HTML
worker_site       | 2021-12-14 18:32:00,166 INFO Adding phase
worker_site       | [2021-12-14 18:32:00,166: INFO/ForkPoolWorker-233] Adding phase
worker_site       | 2021-12-14 18:32:00,166 INFO Current data type is reference_data
worker_site       | [2021-12-14 18:32:00,166: INFO/ForkPoolWorker-233] Current data type is reference_data
worker_site       | 2021-12-14 18:32:00,226 INFO Current data type is scoring_program
worker_site       | [2021-12-14 18:32:00,226: INFO/ForkPoolWorker-233] Current data type is scoring_program
worker_site       | [2021-12-14 18:32:00,283: INFO/ForkPoolWorker-233] Current data type is input_data
worker_site       | 2021-12-14 18:32:00,283 INFO Current data type is input_data
flower            | [I 211214 18:32:01 mixins:231] Connected to amqp://guest:**@rabbit:5671//
worker_site       | 2021-12-14 18:32:04,652 INFO Current data type is starting_kit
worker_site       | [2021-12-14 18:32:04,652: INFO/ForkPoolWorker-233] Current data type is starting_kit
worker_site       | 2021-12-14 18:32:04,733 INFO Current data type is public_data
worker_site       | [2021-12-14 18:32:04,733: INFO/ForkPoolWorker-233] Current data type is public_data
worker_site       | 2021-12-14 18:32:04,746 INFO Current data type is ingestion_program
worker_site       | [2021-12-14 18:32:04,746: INFO/ForkPoolWorker-233] Current data type is ingestion_program
worker_site       | [2021-12-14 18:32:04,756: INFO/ForkPoolWorker-233] There was an error making a Competition dump
worker_site       | 2021-12-14 18:32:04,756 INFO There was an error making a Competition dump
worker_site       | 2021-12-14 18:32:04,757 INFO Traceback (most recent call last):
worker_site       |   File "/usr/local/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 523, in _open
worker_site       |     f = S3Boto3StorageFile(name, mode, self)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 74, in __init__
worker_site       |     self.obj.load()
worker_site       |   File "/usr/local/lib/python3.8/site-packages/boto3/resources/factory.py", line 505, in do_action
worker_site       |     response = action(self, *args, **kwargs)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
worker_site       |     response = getattr(parent.meta.client, operation_name)(*args, **params)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 337, in _api_call
worker_site       |     return self._make_api_call(operation_name, kwargs)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 656, in _make_api_call
worker_site       |     raise error_class(parsed_response, operation_name)
worker_site       | botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
worker_site       | 
worker_site       | During handling of the above exception, another exception occurred:
worker_site       | 
worker_site       | Traceback (most recent call last):
worker_site       |   File "/app/codalab/apps/web/tasks.py", line 1040, in make_modified_bundle
worker_site       |     if data_field.file.name not in list(file_cache.keys()):
worker_site       |   File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/files.py", line 51, in _get_file
worker_site       |     self._file = self.storage.open(self.name, 'rb')
worker_site       |   File "/usr/local/lib/python3.8/site-packages/django/core/files/storage.py", line 38, in open
worker_site       |     return self._open(name, mode)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 526, in _open
worker_site       |     raise IOError('File does not exist: %s' % name)
worker_site       | OSError: File does not exist: ingestion_program/01319259-bad5-443d-a17f-c13406039879/competition/572/1/data/ingestion_pr.zip
worker_site       | 
worker_site       | [2021-12-14 18:32:04,757: INFO/ForkPoolWorker-233] Traceback (most recent call last):
worker_site       |   File "/usr/local/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 523, in _open
worker_site       |     f = S3Boto3StorageFile(name, mode, self)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 74, in __init__
worker_site       |     self.obj.load()
worker_site       |   File "/usr/local/lib/python3.8/site-packages/boto3/resources/factory.py", line 505, in do_action
worker_site       |     response = action(self, *args, **kwargs)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
worker_site       |     response = getattr(parent.meta.client, operation_name)(*args, **params)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 337, in _api_call
worker_site       |     return self._make_api_call(operation_name, kwargs)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 656, in _make_api_call
worker_site       |     raise error_class(parsed_response, operation_name)
worker_site       | botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
worker_site       | 
worker_site       | During handling of the above exception, another exception occurred:
worker_site       | 
worker_site       | Traceback (most recent call last):
worker_site       |   File "/app/codalab/apps/web/tasks.py", line 1040, in make_modified_bundle
worker_site       |     if data_field.file.name not in list(file_cache.keys()):
worker_site       |   File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/files.py", line 51, in _get_file
worker_site       |     self._file = self.storage.open(self.name, 'rb')
worker_site       |   File "/usr/local/lib/python3.8/site-packages/django/core/files/storage.py", line 38, in open
worker_site       |     return self._open(name, mode)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 526, in _open
worker_site       |     raise IOError('File does not exist: %s' % name)
worker_site       | OSError: File does not exist: ingestion_program/01319259-bad5-443d-a17f-c13406039879/competition/572/1/data/ingestion_pr.zip
```

**Comment by Didayolo** [comment]
@aahmd9 Can you try to re-upload the bundle to see if the error persists?

**Comment by aahmd9** [comment]
I will try your suggestion, thank you.
Should i create new competition or could i upload on the actual one?

**Comment by Didayolo** [comment]
I think you should create a new one.

Once your problem is solved you can delete the useless competitions.

**Comment by aahmd9** [comment]
I have re-uploaded the bundle as you suggested and am resubmitting for testing.
 It is now stuck in running status.

**Comment by Didayolo** [comment]
> I will add you to the new competition as admin and the link is the following: https://codalab.lisn.upsaclay.fr/competitions/716?secret_key=81077432-b8d2-4330-ab6a-b20602ce4058 .

I get a 404 error

**Comment by aahmd9** [comment]
I created a new bundle and fixed some problems in the scoring program that are due to the python version. Everything works fine now. 

Thanks for your help

**Comment by Didayolo** [comment]
Great! You're welcome.
