### ISSUE TITLE
Signature mismatch error with Boto on Codalab py2 after storage migration

### ISSUE THREAD

**Issue by dtuantran** [codalab/codalab-competitions#3082]
# Behaviors
After migrating the storage to Minio distributed, the submissions were stuck with this error inside worker_site container :
```
2021-12-03 08:48:25,851 ERROR evaluate_submission dispatch failed (job_id=1071134, submission_id=1038460)
Traceback (most recent call last):
  File "/app/codalab/apps/web/tasks.py", line 786, in evaluate_submission
    task_func(submission, job_id)
  File "/app/codalab/apps/web/tasks.py", line 394, in score
    submission.history_file.save('history.txt', ContentFile('\n'.join(lines)))
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 86, in save
    self.name = self.storage.save(name, content)
  File "/usr/local/lib/python2.7/site-packages/storages/compat.py", line 19, in save
    return super(StorageMixin, self).save(name, content)
  File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 49, in save
    name = self._save(name, content)
  File "/usr/local/lib/python2.7/site-packages/storages/backends/s3boto.py", line 413, in _save
    self._save_content(key, content, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/storages/backends/s3boto.py", line 424, in _save_content
    rewind=True, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/usr/local/lib/python2.7/site-packages/boto/s3/connection.py", line 668, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>submission_history/1038460/a5d8e/history.txt</Key><BucketName>prod-private</BucketName><Resource>/prod-private/submission_history/1038460/a5d8e/history.txt</Resource><RequestId>16BD32724763ABFD</RequestId><HostId>016731cd-3863-432e-a55a-b6fcd5a9d447</HostId></Error>
```
# How to reproduce
By using python2 + Boto and setting up [Minio + proxy](https://docs.min.io/docs/setup-nginx-proxy-with-minio.html), we can reproduce this error as following :
```
import boto
from boto.s3.key import Key
con = boto.connect_s3(host=STORAGE_HOSTNAME, aws_access_key_id='***', aws_secret_access_key='***', calling_format='boto.s3.connection.OrdinaryCallingFormat')
con.auth_region_name="us-east-1"
bk = con.get_bucket('bucket_name')
k = Key(bk)
k.key = "test.txt"
k.set_contents_from_string("test")
```
Then, we get this error:
```
2021-12-09 16:48:27,543 boto [DEBUG]:CanonicalRequest:
PUT
/automl3/test.txt

content-length:66
content-md5:zFmBqPGCRskB66NOb7+Jig==
content-type:text/plain
expect:100-Continue
host:myminio.eu
user-agent:Boto/2.45.0 Python/2.7.15 Linux/4.4.0-178-generic
x-amz-content-sha256:ec1768a4a8d43a7eca3f6335c8690fe1eb05819d3ce83ea10b5436132b78883a
x-amz-date:20211209T164827Z

content-length;content-md5;content-type;expect;host;user-agent;x-amz-content-sha256;x-amz-date
ec1768a4a8d43a7eca3f6335c8690fe1eb05819d3ce83ea10b5436132b78883a
2021-12-09 16:48:27,543 boto [DEBUG]:StringToSign:
AWS4-HMAC-SHA256
20211209T164827Z
20211209/us-east-1/s3/aws4_request
fc2a6f71dd4ad87385a6330ea96dd68e8c99ecb1ebb2a19997b6e29e8ceffe53
2021-12-09 16:48:27,543 boto [DEBUG]:Signature:
c2936afe649ec217a71b7ec8d9bf70558ea1de9ecdcb9e760f6963b5c6c65adc
2021-12-09 16:48:27,544 boto [DEBUG]:Final headers: {'x-amz-content-sha256': 'ec1768a4a8d43a7eca3f6335c8690fe1eb05819d3ce83ea10b5436132b78883a', 'Content-Length': '66', 'Expect': '100-Continue', 'X-Amz-Date': '20211209T164827Z', 'Content-MD5': 'zFmBqPGCRskB66NOb7+Jig==', 'Content-Type': 'text/plain', 'Host': 'myminio.eu', 'Authorization': 'AWS4-HMAC-SHA256 Credential=AZIAIOSAODNN7EX123LE/20211209/us-east-1/s3/aws4_request,SignedHeaders=content-length;content-md5;content-type;expect;host;user-agent;x-amz-content-sha256;x-amz-date,Signature=c2936afe649ec217a71b7ec8d9bf70558ea1de9ecdcb9e760f6963b5c6c65adc', 'User-Agent': 'Boto/2.45.0 Python/2.7.15 Linux/4.4.0-178-generic'}
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 1362, in set_contents_from_filename
    encrypt_key=encrypt_key)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/usr/local/lib/python2.7/site-packages/boto/s3/connection.py", line 668, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>scores.txt</Key><BucketName>automl3</BucketName><Resource>/automl3/scores.txt</Resource><RequestId>16BF2420110894E9</RequestId><HostId>768b42c4-0504-41fc-9410-a8657a97cbcf</HostId></Error>
```
# Cause
Boto calculates the signature with "Expect" field in the HTTP headers `SignedHeaders=content-length;content-md5;content-type;expect;host;user-agent;x-amz-content-sha256;x-amz-date`. The proxy Nginx configurations recommended by Minio doesn't preserve this field. Then, it makes the signature calculated by Minio different.
After trying to preserve "Expect" field, Boto still gets issue with Minio. It doesn't work completely, it usually was hanged on for 60s as described in this issue https://github.com/minio/minio/issues/11950. It caused an other issue for Codalab which slows down or even stuck the submissions.
![image](https://user-images.githubusercontent.com/7440668/150099901-1897ba95-0eed-4a80-9c8f-3762b8ee1f33.png)

# Possible solution
Because the Nginx configurations recommended by Minio works well with Boto3, then upgrading Boto to Boto3 on Codalab py2 could solve this issue.

**Comment by dtuantran** [comment]
Maybe this documentation can help us : https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html
