### ISSUE TITLE
CheXpert Submission  - Old version of torch

### ISSUE THREAD

**Issue by AhmedSimeda** [codalab/codalab-competitions#3086]
When I tried to run my program I got this error message:
---------------------------------------------------
Traceback (most recent call last):
  File "src/src/G_Mans_v1.py", line 3, in <module>
    from coat import coat_mini
  File "/0xc714f8dc6fb241f3be3f149a758ea8cf_dependencies/src/src/coat.py", line 197, in <module>
    class SerialBlock(nn.Module):
  File "/0xc714f8dc6fb241f3be3f149a758ea8cf_dependencies/src/src/coat.py", line 201, in SerialBlock
    drop_path=0., act_layer=nn.GELU, norm_layer=nn.LayerNorm, shared_cpe=None, shared_crpe=None):
AttributeError: module 'torch.nn' has no attribute 'GELU'

**Comment by Didayolo** [comment]
Hi,

This repository concerns the platform itself. To request an upgrade of libraries used in a competition, please contact directly the competition organizers.
Indeed, each competition can have its own evaluation environment.

Thank you for your comprehension.
