### ISSUE TITLE
Unable to create dump for competition

### ISSUE THREAD

**Issue by yael1994** [codalab/codalab-competitions#3137]
i'm trying to create  dump for an unpublished competition.
up until two days ago the procedure worked fine, but now it doesn't work.

<img width="604" alt="image" src="https://user-images.githubusercontent.com/45081145/160633618-6b5c3208-78a1-477d-90cc-672566206571.png">

Chrome version -  99.0.4844.82

**Comment by Didayolo** [comment]
Hello,

Could you please make me admin of the competition so I can check it out?

My username is "pavao".

**Comment by yael1994** [comment]
You are now admin.
Thank you.

**Comment by Didayolo** [comment]
@yael1994 Can you please provide the URL of your competition?

**Comment by Didayolo** [comment]
@yael1994 Thank you for the URL.

I could catch this in the log when trying to make a dump:

```python
worker_site       | 2022-04-08 11:44:57,025 INFO There was an error making a Competition dump
worker_site       | [2022-04-08 11:44:57,025: INFO/ForkPoolWorker-136] Traceback (most recent call last):
worker_site       |   File "/usr/local/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 523, in _open
worker_site       |     f = S3Boto3StorageFile(name, mode, self)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 74, in __init__
worker_site       |     self.obj.load()
worker_site       |   File "/usr/local/lib/python3.8/site-packages/boto3/resources/factory.py", line 505, in do_action
worker_site       |     response = action(self, *args, **kwargs)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
worker_site       |     response = getattr(parent.meta.client, operation_name)(*args, **params)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 337, in _api_call
worker_site       | 2022-04-08 11:44:57,025 INFO Traceback (most recent call last):
worker_site       |   File "/usr/local/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 523, in _open
worker_site       |     f = S3Boto3StorageFile(name, mode, self)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 74, in __init__
worker_site       |     self.obj.load()
worker_site       |   File "/usr/local/lib/python3.8/site-packages/boto3/resources/factory.py", line 505, in do_action
worker_site       |     response = action(self, *args, **kwargs)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
worker_site       |     response = getattr(parent.meta.client, operation_name)(*args, **params)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 337, in _api_call
worker_site       |     return self._make_api_call(operation_name, kwargs)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 656, in _make_api_call
worker_site       |     raise error_class(parsed_response, operation_name)
worker_site       | botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
worker_site       | 
worker_site       | During handling of the above exception, another exception occurred:
worker_site       | 
worker_site       | Traceback (most recent call last):
worker_site       |   File "/app/codalab/apps/web/tasks.py", line 1040, in make_modified_bundle
worker_site       |     if data_field.file.name not in list(file_cache.keys()):
worker_site       |   File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/files.py", line 51, in _get_file
worker_site       |     self._file = self.storage.open(self.name, 'rb')
worker_site       |   File "/usr/local/lib/python3.8/site-packages/django/core/files/storage.py", line 38, in open
worker_site       |     return self._open(name, mode)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 526, in _open
worker_site       |     raise IOError('File does not exist: %s' % name)
worker_site       | OSError: File does not exist: dataset_data_file/435ddfeb-453a-4798-92a8-82f8a647a238/scoring_program_track2.zip
worker_site       | 
worker_site       |     return self._make_api_call(operation_name, kwargs)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 656, in _make_api_call
worker_site       |     raise error_class(parsed_response, operation_name)
worker_site       | botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
worker_site       | 
worker_site       | During handling of the above exception, another exception occurred:
worker_site       | 
worker_site       | Traceback (most recent call last):
worker_site       |   File "/app/codalab/apps/web/tasks.py", line 1040, in make_modified_bundle
worker_site       |     if data_field.file.name not in list(file_cache.keys()):
worker_site       |   File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/files.py", line 51, in _get_file
worker_site       |     self._file = self.storage.open(self.name, 'rb')
worker_site       |   File "/usr/local/lib/python3.8/site-packages/django/core/files/storage.py", line 38, in open
worker_site       |     return self._open(name, mode)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 526, in _open
worker_site       |     raise IOError('File does not exist: %s' % name)
worker_site       | OSError: File does not exist: dataset_data_file/435ddfeb-453a-4798-92a8-82f8a647a238/scoring_program_track2.zip
worker_site       | 
worker_site       | [2022-04-08 11:44:57,028: INFO/ForkPoolWorker-136] Task apps.web.tasks.make_modified_bundle[3d7fd71b-078d-4642-836a-4c80ab107f02] succeeded in 0.0884692738763988s: None
```

I'll investigate the problem.

**Comment by Didayolo** [comment]
I can see that no scoring program is set in the different phases of your competition.

Is that normal? How does the scoring works then?

**Comment by yael1994** [comment]
I will upload the scoring, 
but the dump does not working before I removed the scoring.
