### ISSUE TITLE
Submission fails with local CodaLab instance

### ISSUE THREAD

**Issue by mariusbrinkmann** [codalab/codalab-competitions#3144]
Hello,

I'm running a CodaLab instance locally on my computer which is connected to a Microsoft Azure blob storage.

After starting the instance using `docker-compose up -d && docker-compose logs -f`, I can upload a competition bundle which is uploaded to the Azure storage successfully.

However, when uploading a submission, I receive the following error in the logs:
```python
django            | 2022-04-05 14:56:41,059 INFO Saving competition submission.
django            | 2022-04-05 14:56:41,313 INFO This is a new submission, getting the submission number.
django            | 2022-04-05 14:56:41,318 INFO This is submission number 0, and 0 submissions have failed
django            | 2022-04-05 14:56:41,319 INFO Submission number below maximum.
django            | 2022-04-05 14:56:41,319 INFO Checking submissions per day count
django            | 2022-04-05 14:56:41,320 INFO Count is 0 and maximum is 15
django            | 2022-04-05 14:56:41,412 ERROR Internal Server Error: /api/competition/1/submission
django            | Traceback (most recent call last):
django            |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 41, in inner
django            |     response = get_response(request)
django            |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 187, in _get_response
django            |     response = self.process_exception_by_middleware(e, request)
django            |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 185, in _get_response
django            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django            |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
django            |     return view_func(*args, **kwargs)
django            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 103, in view
django            |     return self.dispatch(request, *args, **kwargs)
django            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 483, in dispatch
django            |     response = self.handle_exception(exc)
django            |   File "/app/codalab/apps/api/views/competition_views.py", line 643, in handle_exception
django            |     return super(CompetitionSubmissionViewSet, self).handle_exception(exc)
django            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 443, in handle_exception
django            |     self.raise_uncaught_exception(exc)
django            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in dispatch
django            |     response = handler(request, *args, **kwargs)
django            |   File "/app/codalab/apps/api/views/competition_views.py", line 572, in create
django            |     temp_obj = self.perform_create(serializer, request)
django            |   File "/app/codalab/apps/api/views/competition_views.py", line 635, in perform_create
django            |     obj.save()
django            |   File "/app/codalab/apps/web/models.py", line 1585, in save
django            |     sub_size = get_submission_size(self)
django            |   File "/app/codalab/apps/web/utils.py", line 213, in get_submission_size
django            |     total += get_filefield_size(submission, 'file', aws_attr='s3_file', s3direct=True)
django            | TypeError: unsupported operand type(s) for +=: 'int' and 'str'
```
Executing `docker-compose ps -a` gives the following results:
```python
     Name                   Command               State                                                                 Ports
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
django           bash /app/docker/run_django.sh   Up       0.0.0.0:8000->8000/tcp,:::8000->8000/tcp
flower           /usr/bin/dumb-init /opt/ce ...   Up       0.0.0.0:5555->5555/tcp,:::5555->5555/tcp
memcached        docker-entrypoint.sh /usr/ ...   Up       11211/tcp
nginx            /docker-entrypoint.sh bash ...   Up       0.0.0.0:443->443/tcp,:::443->443/tcp, 0.0.0.0:80->80/tcp,:::80->80/tcp
postgres         docker-entrypoint.sh postgres    Up       5432/tcp
rabbit           docker-entrypoint.sh bash  ...   Up       15671/tcp, 0.0.0.0:15672->15672/tcp,:::15672->15672/tcp, 25672/tcp, 4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp,:::5672->5672/tcp
worker_compute   /bin/bash                        Exit 0
worker_site      sh /app/docker/run_site.sh       Up
```

Is it correct that the status of `worker_compute` is `Exit 0`? I'm using the `codalab/codalab-legacy:latest` docker container for the compute worker.  Do I have to connect `worker_compute` to the blob storage?

Testing the CodaLab instance with `docker exec -it django bash && py.test` outputs `262 passed, 775 warnings in 47.78s`.

**Comment by Didayolo** [comment]
> I'm using the codalab/codalab-legacy:latest docker container for the compute worker.

What do you mean?

It is an external compute worker?

If so, the Docker image of the worker itself is supposed to be `codalab/competitions-v1-compute-worker:1.1.5` (see https://github.com/codalab/codalab-competitions/wiki/User_Using-your-own-compute-workers).

`codalab/codalab-legacy` is a **competition** Docker image, so it should only be linked to a competition, not to the setup of a compute worker.

If it is the default compute worker, I think it is supposed to be setup automatically when you use `docker-compose up -d`

**Comment by mariusbrinkmann** [comment]
Thank you, that was the mistake. I did not know that there are two different kinds of Docker images. Now it is working.
