### ISSUE TITLE
Flower: Connection Refused

### ISSUE THREAD

**Issue by seerwright** [codalab/codalab-competitions#3182]
New to Codalab and trying to get the platform to run. Storage is configured and the stack seems to run without complaint except for Flower. 

**What's the problem?**

Flower does not seem to be connecting to RabbitMQ, which prevents Codalab from functioning properly. 

**What have I tried?**

- Enabling `rabbitmq-plugins enable rabbitmq_management`, but it was already enabled
- Clean install on a new machine instance
- Visited _Read the Docs Debugging_
- Tried changing the Rabbit port from 5672 to 5671, which I saw in the production .env
- Searching online, which yielded suggestions about CORS, user permissions in Rabbit, and **not** containerizing Flower
- Checking for relevant Issues in this repo. I found none

**Are all services available in monitoring?**

- Flower's monitoring works EXCEPT for the Broker view. That spins and never comes up, presumably because the connection is refused. (See stack trace below.)
- Rabbit appears to have fully functioning monitoring.

**Stack trace**
```
flower            |       File "/usr/local/lib/python3.5/site-packages/amqp/connection.py", line 186, in Transport
flower            |         return create_transport(host, connect_timeout, ssl)
flower            |       File "/usr/local/lib/python3.5/site-packages/amqp/transport.py", line 299, in create_transport
flower            |         return TCPTransport(host, connect_timeout)
flower            |       File "/usr/local/lib/python3.5/site-packages/amqp/transport.py", line 95, in __init__
flower            |         raise socket.error(last_err)
flower            |     OSError: [Errno 111] Connection refused
flower            | [E 220603 02:48:23 gen:661] Multiple exceptions in yield list
flower            |     Traceback (most recent call last):
flower            |       File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 656, in callback
flower            |         result_list.append(f.result())
flower            |       File "/usr/local/lib/python3.5/concurrent/futures/_base.py", line 398, in result
flower            |         return self.__get_result()
flower            |       File "/usr/local/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
flower            |         raise self._exception
flower            |       File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
flower            |         result = self.fn(*self.args, **self.kwargs)
flower            |       File "/usr/local/lib/python3.5/site-packages/celery/app/control.py", line 109, in conf
flower            |         return self._request('dump_conf', with_defaults=with_defaults)
flower            |       File "/usr/local/lib/python3.5/site-packages/celery/app/control.py", line 71, in _request
flower            |         timeout=self.timeout, reply=True,
flower            |       File "/usr/local/lib/python3.5/site-packages/celery/app/control.py", line 316, in broadcast
flower            |         limit, callback, channel=channel,
flower            |       File "/usr/local/lib/python3.5/site-packages/kombu/pidbox.py", line 283, in _broadcast
flower            |         chan = channel or self.connection.default_channel
flower            |       File "/usr/local/lib/python3.5/site-packages/kombu/connection.py", line 766, in default_channel
flower            |         self.connection
flower            |       File "/usr/local/lib/python3.5/site-packages/kombu/connection.py", line 751, in connection
flower            |         self._connection = self._establish_connection()
flower            |       File "/usr/local/lib/python3.5/site-packages/kombu/connection.py", line 706, in _establish_connection
flower            |         conn = self.transport.establish_connection()
flower            |       File "/usr/local/lib/python3.5/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
flower            |         conn = self.Connection(**opts)
flower            |       File "/usr/local/lib/python3.5/site-packages/amqp/connection.py", line 165, in __init__
flower            |         self.transport = self.Transport(host, connect_timeout, ssl)
flower            |       File "/usr/local/lib/python3.5/site-packages/amqp/connection.py", line 186, in Transport
flower            |         return create_transport(host, connect_timeout, ssl)
flower            |       File "/usr/local/lib/python3.5/site-packages/amqp/transport.py", line 299, in create_transport
flower            |         return TCPTransport(host, connect_timeout)
flower            |       File "/usr/local/lib/python3.5/site-packages/amqp/transport.py", line 95, in __init__
flower            |         raise socket.error(last_err)
flower            |     OSError: [Errno 111] Connection refused
flower            | [E 220603 02:48:25 events:123] Failed to capture events: '[Errno 111] Connection refused', trying again in 4 seconds.
flower            | [E 220603 02:48:29 events:123] Failed to capture events: '[Errno 111] Connection refused', trying again in 8 seconds.
flower            | [I 220603 02:48:37 mixins:231] Connected to amqp://guest:**@rabbit:5672//
flower            | [E 220603 02:53:38 events:123] Failed to capture events: 'list indices must be integers or slices, not str', trying again in 1 seconds.
flower            | [I 220603 02:53:39 mixins:231] Connected to amqp://guest:**@rabbit:5672//
```

**Comment by seerwright** [comment]
UPDATE

A lot can go wrong when deploying Codalab and the readme has serious gaps. I don't know what I did to resolve this, but here's an overview of what I ultimately did to get Codalab working:

- Deploy MinIO on a separate VM. I had issues with it being on the same machine as a docker-compose alongside the Codalab docker-compose. 
- Test your MinIO locally with a native install of `mc` to make sure the server side truly works. Make sure you set the correct policies for each bucket per the notes on this repo.
- Deploy Codalab on a VM other than MinIO. Maybe this isn't necessary, but it was the only thing (I am aware of) that I did differently.
- Use the .env_sample and 1) delete ALL storage params except MinIO
- Once it is up, register, then use the [dev admin notes](https://github.com/codalab/codalab-competitions/wiki/Dev_Administrator-Procedures) to verify email manually and make yourself a super user
- To check, visit the monitoring and make sure storage analytics are working. That's your first clue that MinIO isn't working right. Then try to upload a dataset. It should work. Finally, try to upload a bundle. I made one using the create competition script.
