### ISSUE TITLE
Error: "Failed, competition phase is being migrated, please try again in a few minutes"

### ISSUE THREAD

**Issue by DustinCarrion** [codalab/codalab-competitions#3190]
I have a two phases competition (https://codalab.lisn.upsaclay.fr/competitions/5635):

**First phase:** Started on June 10, 2022.
**Second phase:** Will start on September 1, 2022.

For the second phase, the last submission of the first phase should be automatically forwarded. Therefore, in the second phase I selected the `auto migration` option.  However, sometimes no submissions can be done because the platform displays the message:
```
Failed, competition phase is being migrated, please try again in a few minutes
```
I have tried to solve the problem by removing the `auto migration`, but nothing seems to work. Submission 147651 can be used as example submission.

**Comment by Didayolo** [comment]
Indeed I face the error when I try to submit. I'm going to investigate the issue.

**Comment by Didayolo** [comment]
Not sure if it is linked, but I paste this for record.

When trying to make a dump, it fails:

```
worker_site       | 2022-06-30 21:38:16,568 INFO There was an error making a Competition dump
|...]
worker_site       | botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
```

```
worker_site       | Traceback (most recent call last):
worker_site       |   File "/app/codalab/apps/web/tasks.py", line 1040, in make_modified_bundle
worker_site       |     if data_field.file.name not in list(file_cache.keys()):
worker_site       |   File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/files.py", line 51, in _get_file
worker_site       |     self._file = self.storage.open(self.name, 'rb')
worker_site       |   File "/usr/local/lib/python3.8/site-packages/django/core/files/storage.py", line 38, in open
worker_site       |     return self._open(name, mode)
worker_site       |   File "/usr/local/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 526, in _open
worker_site       |     raise IOError('File does not exist: %s' % name)
worker_site       | OSError: File does not exist: dataset_data_file/dca89a18-9b62-4b04-92c5-cf006696cb5c/starting_kit.zip
```

**Comment by Didayolo** [comment]
Related issue: https://github.com/codalab/codalab-competitions/issues/3064

Many things in common here

**Comment by Didayolo** [comment]
Last idea, a submission is currently running on the final phase, maybe we need it to terminate.

I see that you was able to make submissions 2 hours ago. On my side no submissions worked.

Once again, re-uploading the bundle from scratch would probably solve the issue. It is inconvenient, however if it is necessary it is important to do it before the start of the competition.

**Comment by DustinCarrion** [comment]
After some examination, I think the problem can be caused by the Auto migration property that it was not doing what I was expecting. My expected behavior was that once the first phase finishes, the last submission is automatically forwarded to the second phase. However, what really happens is that all submissions are forwarded to the second phase even though the second phase has not started yet. For this reason, I verified if this property can be activated and deactivated at any time, and indeed it is possible to do it. Therefore, as a temporal solution, I deactivated the Auto migration property in the real competition, and I will activate it on the last day of the competition.

Regarding the dumps, I was about to open another issue for that because dumps are not working; I have tried in 4 competitions without success.

**Comment by AliRajaei95** [comment]
I have the same problem in my competition: [https://codalab.lisn.upsaclay.fr/competitions/12420]
The weird thing is that the compeition was running fine until Thursday 24-Sep-2023. But now all participans get the error: "Failed, competition phase is being migrated, please try again in a few minutes". 
Initially, Auto-migration was checked for the competition. From today we're getting the above error. So I tried unchecking the Auto-migration, but still we get the error.
