### ISSUE TITLE
HTTP error when running cl-competitiond

### ISSUE THREAD

**Issue by entslscheia** [codalab/codalab-competitions#3210]
Hi,

We have host our [GrailQA competition](https://dki-lab.github.io/GrailQA/) on CodaLab for a while, and everything looked fine. However, recently when I tried to run the command `cl-competitiond -v config.yml output.json` to evaluate new submissions as usual, it reported the following error message:

```
[INFO] 2022-08-06 10:47:52,884: Running batch competition evaluation
[DEBUG] 2022-08-06 10:47:53,413: Collecting latest submissions
[DEBUG] 2022-08-06 10:48:08,146: Already mimicked last submission by SivilTaram.
[DEBUG] 2022-08-06 10:48:08,146: Already mimicked last submission by xiye17.
[DEBUG] 2022-08-06 10:48:08,146: Already mimicked last submission by DaoguangZan.
[DEBUG] 2022-08-06 10:48:08,146: Already mimicked last submission by liusheng.
[DEBUG] 2022-08-06 10:48:08,147: Already mimicked last submission by yhshu.
[DEBUG] 2022-08-06 10:48:08,147: Already mimicked last submission by zg.
[DEBUG] 2022-08-06 10:48:08,147: Already mimicked last submission by BATCAKE.
[INFO] 2022-08-06 10:48:08,147: Mimicking submission for YuGu
Traceback (most recent call last):
  File "/home/gu.826/.local/lib/python3.6/site-packages/codalab/client/json_api_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/home/gu.826/.local/lib/python3.6/site-packages/codalab/client/json_api_client.py", line 466, in create
    data=self._pack_document(data if isinstance(data, list) else [data], resource_type),
  File "/home/gu.826/.local/lib/python3.6/site-packages/scripts/competitiond.py", line 73, in _make_request
    return super(JsonApiClientWithRetry, self)._make_request(*args, **kwargs)
  File "/home/gu.826/.local/lib/python3.6/site-packages/codalab/worker/rest_client.py", line 103, in _make_request
    with closing(urllib.request.urlopen(request, timeout=timeout_seconds)) as response:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gu.826/.local/bin/cl-competitiond", line 11, in <module>
    sys.exit(main())
  File "/home/gu.826/.local/lib/python3.6/site-packages/scripts/competitiond.py", line 844, in main
    comp.run_once()
  File "/home/gu.826/.local/lib/python3.6/site-packages/scripts/competitiond.py", line 738, in run_once
    predict_bundle = self.run_prediction(submit_bundle)
  File "/home/gu.826/.local/lib/python3.6/site-packages/scripts/competitiond.py", line 482, in run_prediction
    predict_bundle = find_mimicked(mimic_bundles(dry_run=False, **mimic_args))
  File "/home/gu.826/.local/lib/python3.6/site-packages/codalab/lib/bundle_util.py", line 244, in mimic_bundles
    recurse(old_output)
  File "/home/gu.826/.local/lib/python3.6/site-packages/codalab/lib/bundle_util.py", line 152, in recurse
    for dep in old_info['dependencies']
  File "/home/gu.826/.local/lib/python3.6/site-packages/codalab/lib/bundle_util.py", line 152, in <listcomp>
    for dep in old_info['dependencies']
  File "/home/gu.826/.local/lib/python3.6/site-packages/codalab/lib/bundle_util.py", line 231, in recurse
    new_info = client.create('bundles', new_info, params=params)
  File "/home/gu.826/.local/lib/python3.6/site-packages/codalab/client/json_api_client.py", line 38, in wrapper
    sys.exc_info()[2],
  File "/home/gu.826/.local/lib/python3.6/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home/gu.826/.local/lib/python3.6/site-packages/codalab/client/json_api_client.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "/home/gu.826/.local/lib/python3.6/site-packages/codalab/client/json_api_client.py", line 466, in create
    data=self._pack_document(data if isinstance(data, list) else [data], resource_type),
  File "/home/gu.826/.local/lib/python3.6/site-packages/scripts/competitiond.py", line 73, in _make_request
    return super(JsonApiClientWithRetry, self)._make_request(*args, **kwargs)
  File "/home/gu.826/.local/lib/python3.6/site-packages/codalab/worker/rest_client.py", line 103, in _make_request
    with closing(urllib.request.urlopen(request, timeout=timeout_seconds)) as response:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
codalab.client.json_api_client.JsonApiException: Unable to create bundles: Internal Server Error - Internal Server Error
```
I don't think I have made any changes to the config file `config.yml` during the past year. So this error is quite strange to me. 

Any suggestions would be greatly appreciated!

Thanks & Regards,
Yu

**Comment by entslscheia** [comment]
Previously I was using `CodaLab 0.5.27`. I thought it might be some outdated version issue, so I updated it to the latest version, but the problem remains.

**Comment by entslscheia** [comment]
I managed to hack into the code and found the http request that caused the error:
```
https://worksheets.codalab.org/rest/bundles?worksheet=0xXXXXXXXXXXXXXXXXXXXX&detached=1
```
This is the url used in the statement `with closing(urllib.request.urlopen(request, timeout=timeout_seconds)) as response:`.
I masked the bundle id, because it's actually the bundle that stores all submissions, which is a private bundle only visible to me.

**Comment by entslscheia** [comment]
> Hi @entslscheia,
> 
> I am a bit confused by your issue. Are you using [CodaLab Competitions](https://codalab.lisn.upsaclay.fr/) or [CodaLab Worksheets](https://worksheets.codalab.org/)?
> 
> If you are using CodaLab Competitions, then the command line and codalab package are irrelevant.
> 
> If you are using CodaLab Worksheets, please raise your issue in the following repository: https://github.com/codalab/codalab-worksheets Indeed, the two projects are managed by two independent teams.

Hi,

Thanks for your response.
I am using the command `cl-competitiond`. Shouldn't it be a part of the CodaLab package?
However, I guess this is not the main point. The main point is that this command has worked for me for around two years, but recently it began to report an error and I am not sure why. I looked into the source code and found that this is because the the `specs` argument is missing in the HTTP request.

Best,
Yu

**Comment by entslscheia** [comment]
> Hi @entslscheia,
> 
> I am a bit confused by your issue. Are you using [CodaLab Competitions](https://codalab.lisn.upsaclay.fr/) or [CodaLab Worksheets](https://worksheets.codalab.org/)?
> 
> If you are using CodaLab Competitions, then the command line and codalab package are irrelevant.
> 
> If you are using CodaLab Worksheets, please raise your issue in the following repository: https://github.com/codalab/codalab-worksheets Indeed, the two projects are managed by two independent teams.

Hi,

Thanks for your response!
I will raise my issue in Codalab-worksheets.
