### ISSUE TITLE
Dumping fails on some competition

### ISSUE THREAD

**Issue by Didayolo** [codalab/codalab-competitions#3287]
<img width="942" alt="Capture d’écran 2022-11-15 à 17 53 04" src="https://user-images.githubusercontent.com/11784999/201979141-cee36fd8-6e6d-49e8-a67e-60fc447eedba.png">

Example of such competition:
https://codalab.lisn.upsaclay.fr/competitions/3627/dumps/

**Comment by hazirbas** [comment]
Hi, I am having the same issue and would like to transfer my competition to Codabench as soon as possible. How can I get some support here?
https://competitions.codalab.org/competitions/17807/dumps/

**Comment by Didayolo** [comment]
Hi @hazirbas,

I am currently unavailable to help with this matter, but @ObadaS may be, or may be able to redirect the issue to the right person.

Best regards.

**Comment by hazirbas** [comment]
Hi @ObadaS , can you help us with this as we are rushing to move the competition for the CVPR deadline?

**Comment by Didayolo** [comment]
@hazirbas Have you made any progress on this? If no, can you please share your CodaLab username so I can investigate the issue?

**Comment by hazirbas** [comment]
@Didayolo no progress, my username is hazirbas.

**Comment by Didayolo** [comment]
Some logs:

```python
worker_site  | [2025-11-26 01:42:40,399: INFO/MainProcess] Received task: apps.web.tasks.make_modified_bundle[6f4d6330-e5ea-4a1e-a88d-8979572a4c22]
worker_site  | 2025-11-26 01:42:40,409 INFO Creating Competion dump
worker_site  | [2025-11-26 01:42:40,409: INFO/Worker-6] Creating Competion dump
worker_site  | 2025-11-26 01:42:40,421 INFO Adding end-date
worker_site  | [2025-11-26 01:42:40,421: INFO/Worker-6] Adding end-date
worker_site  | 2025-11-26 01:42:40,444 INFO Adding HTML
worker_site  | [2025-11-26 01:42:40,444: INFO/Worker-6] Adding HTML
worker_site  | [2025-11-26 01:42:40,448: INFO/Worker-6] Adding HTML
worker_site  | 2025-11-26 01:42:40,448 INFO Adding HTML
worker_site  | [2025-11-26 01:42:40,452: INFO/Worker-6] Adding HTML
worker_site  | 2025-11-26 01:42:40,452 INFO Adding HTML
worker_site  | 2025-11-26 01:42:40,456 INFO Adding HTML
worker_site  | [2025-11-26 01:42:40,456: INFO/Worker-6] Adding HTML
worker_site  | 2025-11-26 01:42:40,460 INFO Adding HTML
worker_site  | [2025-11-26 01:42:40,460: INFO/Worker-6] Adding HTML
worker_site  | 2025-11-26 01:42:40,493 INFO Adding phase
worker_site  | [2025-11-26 01:42:40,493: INFO/Worker-6] Adding phase
worker_site  | 2025-11-26 01:42:40,493 INFO Current data type is reference_data
worker_site  | [2025-11-26 01:42:40,493: INFO/Worker-6] Current data type is reference_data
[...]
worker_site  | 2025-11-26 01:44:01,491 INFO There was an error making a Competition dump
worker_site  | [2025-11-26 01:44:01,491: INFO/Worker-6] There was an error making a Competition dump
worker_site  | 2025-11-26 01:44:01,493 INFO Traceback (most recent call last):
worker_site  |   File "/app/codalab/apps/web/tasks.py", line 1018, in make_modified_bundle
worker_site  |     if data_field.file.name not in file_cache.keys():
worker_site  |   File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _get_file
worker_site  |     self._file = self.storage.open(self.name, 'rb')
worker_site  |   File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 33, in open
worker_site  |     return self._open(name, mode)
worker_site  |   File "/usr/local/lib/python2.7/site-packages/storages/backends/s3boto.py", line 384, in _open
worker_site  |     f = self.file_class(name, mode, self)
worker_site  |   File "/usr/local/lib/python2.7/site-packages/storages/backends/s3boto.py", line 92, in __init__
worker_site  | [2025-11-26 01:44:01,493: INFO/Worker-6] Traceback (most recent call last):
worker_site  |   File "/app/codalab/apps/web/tasks.py", line 1018, in make_modified_bundle
worker_site  |     if data_field.file.name not in file_cache.keys():
worker_site  |   File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _get_file
worker_site  |     self._file = self.storage.open(self.name, 'rb')
worker_site  |   File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 33, in open
worker_site  |     return self._open(name, mode)
worker_site  |   File "/usr/local/lib/python2.7/site-packages/storages/backends/s3boto.py", line 384, in _open
worker_site  |     f = self.file_class(name, mode, self)
worker_site  |   File "/usr/local/lib/python2.7/site-packages/storages/backends/s3boto.py", line 92, in __init__
worker_site  |     self.key = storage.bucket.get_key(self._storage._encode_name(name))
worker_site  |   File "/usr/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 193, in get_key
worker_site  |     key, resp = self._get_key_internal(key_name, headers, query_args_l)
worker_site  |   File "/usr/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 200, in _get_key_internal
worker_site  |     query_args=query_args)
worker_site  |   File "/usr/local/lib/python2.7/site-packages/boto/s3/connection.py", line 668, in make_request
worker_site  |     retry_handler=retry_handler
worker_site  |   File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
worker_site  |     retry_handler=retry_handler)
worker_site  |   File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1030, in _mexe
worker_site  |     raise ex
worker_site  | SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
worker_site  | 
worker_site  |     self.key = storage.bucket.get_key(self._storage._encode_name(name))
worker_site  |   File "/usr/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 193, in get_key
worker_site  |     key, resp = self._get_key_internal(key_name, headers, query_args_l)
worker_site  |   File "/usr/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 200, in _get_key_internal
worker_site  |     query_args=query_args)
worker_site  |   File "/usr/local/lib/python2.7/site-packages/boto/s3/connection.py", line 668, in make_request
worker_site  |     retry_handler=retry_handler
worker_site  |   File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
worker_site  |     retry_handler=retry_handler)
worker_site  |   File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1030, in _mexe
worker_site  |     raise ex
worker_site  | SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
worker_site  | 
worker_site  | [2025-11-26 01:44:01,577: INFO/MainProcess] Task apps.web.tasks.make_modified_bundle[6f4d6330-e5ea-4a1e-a88d-8979572a4c22] succeeded in 81.1758210957s: None
```

**Comment by Didayolo** [comment]
@hazirbas 

I think a work-around is the following:

- Get the original bundle uploaded to CodaLab (if you don't have it, we may be able to retrieve it in the storage)
- Download most recent versions of `reference_data` and `scoring_program` (in "My Datasets" interface : https://competitions.codalab.org/my/datasets/)
- Update the original bundle with these elements, and potentially also settings and documentation pages from the "EDIT" menu

As the competition is quite old, it may need some adaptation anyway to work fine on Codabench.

**Comment by hazirbas** [comment]
@Didayolo gotcha, well I will look into it, but may also prefer to end the competition at this point. Also yes I would need the original bundle from the storage.

**Comment by Didayolo** [comment]
@ObadaS Any tip for getting the original bundle from the storage?

**Comment by ObadaS** [comment]
Unfortunately it's not that simple since the data is saved with different keys in MinIO. We would need to fix the SSL error by either updating some packages like `requests` or import the code from the autoDLMinio branch so that the website uses the `mc` command instead of python package.

**Comment by Didayolo** [comment]
OK so maybe this one needs to be manually ported to Codabench...

**Comment by hazirbas** [comment]
Hi @Didayolo and @ObadaS, can you help me with this?

**Comment by Didayolo** [comment]
> Hi [@Didayolo](https://github.com/Didayolo) and [@ObadaS](https://github.com/ObadaS), can you help me with this?

Sure.

What is you current situation? You do not have access to the original bundle?

The procedure basically will be to download all relevant files from CodaLab (scoring programs, datasets, etc.) and create a new bundle to be uploaded on Codabench. We can set up a quick call if necessary to help you with this. Feel free to contact us by email (info@codalab.org) to share contact information.
