### ISSUE TITLE
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

### ISSUE THREAD

**Issue by marcevrard** [codalab/codalab-competitions#3288]
We're organizing a competition. We migrated a previous competition and when we try to submit a `.zip` file to test the system, we receive this error:

```
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python3.9/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "/tmp/codalab/tmpvdUigf/run/program/score.py", line 21, in 
    import libscores
  File "/tmp/codalab/tmpvdUigf/run/program/libscores.py", line 35, in 
    from pip import get_installed_distributions as lib
ImportError: cannot import name 'get_installed_distributions' from 'pip' (/opt/conda/lib/python3.9/site-packages/pip/__init__.py)
```
We also tried on a previous version and got the same error message.

**Comment by Didayolo** [comment]
Hello Marc,

I think it is due to the fact [the default competition Docker image got updated](https://groups.google.com/g/codalab-competitions/c/ePhMJKpcDFM/m/NhAXbyNwBgAJ).

To fix this, go to the editor, and put `codalab/codalab-legacy:py2` in the field "Competition docker image".

Best regards,

Adrien

**Comment by marcevrard** [comment]
Hello Adrien,

It works, thank you for the quick and precise reply!

Best,
Marc

**Comment by Didayolo** [comment]
Great news!
