### ISSUE TITLE
No such file or dictionary 

### ISSUE THREAD

**Issue by Khinchine** [codalab/codalab-competitions#3336]
When I submit results in Factify, I get the error as follows:

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpyk2PLs/run/program/evaluation.py", line 30, in 
    truth = pd.read_csv(truth_file)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'/tmp/codalab/tmpyk2PLs/run/input/ref/scores.csv' does not exist: b'/tmp/codalab/tmpyk2PLs/run/input/ref/scores.csv'

**Comment by Khinchine** [comment]
This is my submission file:
[ref.zip](https://github.com/codalab/codalab-competitions/files/10953195/ref.zip)

**Comment by Didayolo** [comment]
Are you the only one getting this error?

I think the `[...]/run/input/ref` folder is supposed to contain the ground truth of the task. If something is missing here, it means that the problem comes from the competition.

**Comment by Khinchine** [comment]
I'm not sure.
I've tried a lot of submission methods to no avail. I am trying to contact the competition official consultation

**Comment by Khinchine** [comment]
> Collaborator

I'm not sure.
I've tried a lot of submission methods to no avail. I am trying to contact the competition official consultation

**Comment by Didayolo** [comment]
OK. I'm pretty sure the problem comes from the reference data or scoring program, and is therefore on the side of organizers.

What is the URL to the competition?
