### ISSUE TITLE
URGENT: Cannot import evaluate package from huggingface

### ISSUE THREAD

**Issue by chiyuzhang94** [codalab/codalab-competitions#3419]
Hi,

I cannot import evaluate package from huggingface in my competition evaluation program. 
I tried last month. It worked for me. But when I tried again today, it doesn't work. 

Here is a link to my competition.
https://codalab.lisn.upsaclay.fr/competitions/14643
https://codalab.lisn.upsaclay.fr/competitions/14648

We are running a shared task and are now is the testing phase. Please help us fix this issue ASAP. 

We load evaluate package in our scripts:
```
import json
import os, sys
import glob
import subprocess

def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])
install("evaluate")

import evaluate 
bleu_score = evaluate.load("bleu")
```

Here is the error:
```
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Traceback (most recent call last):
  File "/tmp/codalab/tmps2T0Pw/run/program/evaluation.py", line 10, in 
    import evaluate 
  File "/opt/conda/lib/python3.9/site-packages/evaluate/__init__.py", line 29, in 
    from .evaluation_suite import EvaluationSuite
  File "/opt/conda/lib/python3.9/site-packages/evaluate/evaluation_suite/__init__.py", line 7, in 
    from datasets import Dataset, DownloadMode, load_dataset
  File "/opt/conda/lib/python3.9/site-packages/datasets/__init__.py", line 22, in 
    from .arrow_dataset import Dataset
  File "/opt/conda/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 66, in 
    from .arrow_reader import ArrowReader
  File "/opt/conda/lib/python3.9/site-packages/datasets/arrow_reader.py", line 30, in 
    from .download.download_config import DownloadConfig
  File "/opt/conda/lib/python3.9/site-packages/datasets/download/__init__.py", line 9, in 
    from .download_manager import DownloadManager, DownloadMode
  File "/opt/conda/lib/python3.9/site-packages/datasets/download/download_manager.py", line 32, in 
    from ..utils.file_utils import cached_path, get_from_cache, hash_url_to_filename, is_relative_path, url_or_path_join
  File "/opt/conda/lib/python3.9/site-packages/datasets/utils/file_utils.py", line 348, in 
    class TqdmCallback(fsspec.callbacks.TqdmCallback):
AttributeError: module 'fsspec.callbacks' has no attribute 'TqdmCallback'
```

**Comment by chiyuzhang94** [comment]
Hi @Didayolo ,

Thanks for your reply. 

I didn't use any specific docker. I think it is the default. Could you please point me how I can set up the docker?

Best,
Chiyu

**Comment by Didayolo** [comment]
Hi,

You can either create an image from scratch using a Dockerfile, or update the default image and upload the new version on your own DockerHub account.

Once you have a docker image with the desired libraries on DockerHub, you can set it in your competition using the editor ("EDIT" menu).

You can refer to this wiki entry for more information:
https://github.com/codalab/codalab-competitions/wiki/User_Docker

**Comment by chiyuzhang94** [comment]
Thanks. We solved this issue by adding `install("datasets==2.11.0")` before `install("evaluate")`.
