### ISSUE TITLE
Website not Available

### ISSUE THREAD

**Issue by crockwell** [codalab/codalab-competitions#3475]
Opening a new issue for visibility. I also commented this in https://github.com/codalab/codalab-competitions/issues/3164#issuecomment-2000095328_

Hi,

I'm trying to download https://competitions.codalab.org/competitions/32377#participate

When I try to sign in using my existing account it says "The login and/or password you specified are not correct."; when I try to forget password it says "The e-mail address is not assigned to any user account" and finally when I try to create a new account it says "The CodaLab site is currently unavailable." This has been the case all week. Can someone please assist? I just need to download the dataset.

Thanks,
Chris

**Comment by Didayolo** [comment]
Thank you for reporting the problem. We are looking into it.

https://competitions.codalab.org/ is an old Python 2 server, kept as archive. Creating an account, a competition or making submission is disabled. However, login is supposed to be working.

Just for your information, here are the active servers:
- https://codalab.lisn.fr/
- https://codabench.org/

**Comment by Didayolo** [comment]
Logs for record. Possibly due to the new network and proxy configuration.

```python
django       | postgres: forward host lookup failed: Unknown host
django       | postgres: forward host lookup failed: Unknown host
worker_site  | [2024-03-18 11:59:15,878: INFO/MainProcess] Received task: apps.web.tasks.do_phase_migrations[41ce31d1-a9ab-42f0-9938-41f14936e650]
worker_site  | [2024-03-18 11:59:15,880: INFO/MainProcess] Events of group {task} enabled by remote.
worker_site  | [2024-03-18 11:59:15,959: ERROR/MainProcess] Task apps.web.tasks.do_phase_migrations[41ce31d1-a9ab-42f0-9938-41f14936e650] raised unexpected: OperationalError('could not translate host name "postgres" to address: Name or service not known\n',)
worker_site  | Traceback (most recent call last):
worker_site  |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
worker_site  |     R = retval = fun(*args, **kwargs)
worker_site  |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
worker_site  |     return self.run(*args, **kwargs)
worker_site  |   File "/app/codalab/apps/web/tasks.py", line 884, in do_phase_migrations
worker_site  |     logger.info("Checking {} competitions for phase migrations.".format(len(competitions)))
worker_site  |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
worker_site  |     self._fetch_all()
worker_site  |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
worker_site  |     self._result_cache = list(self.iterator())
worker_site  |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
worker_site  |     for row in compiler.results_iter():
worker_site  |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
worker_site  |     for rows in self.execute_sql(MULTI):
worker_site  |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 785, in execute_sql
worker_site  |     cursor = self.connection.cursor()
worker_site  |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 160, in cursor
worker_site  |     cursor = self.make_debug_cursor(self._cursor())
worker_site  |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 132, in _cursor
worker_site  |     self.ensure_connection()
worker_site  |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 127, in ensure_connection
worker_site  |     self.connect()
worker_site  |   File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
worker_site  |     six.reraise(dj_exc_type, dj_exc_value, traceback)
worker_site  |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 127, in ensure_connection
worker_site  |     self.connect()
worker_site  |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 115, in connect
worker_site  |     self.connection = self.get_new_connection(conn_params)
worker_site  |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 115, in get_new_connection
worker_site  |     return Database.connect(**conn_params)
worker_site  |   File "/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 126, in connect
worker_site  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
worker_site  | OperationalError: could not translate host name "postgres" to address: Name or service not known
worker_site  | 
django       | postgres: forward host lookup failed: Unknown host
django       | postgres: forward host lookup failed: Unknown host
django       | postgres: forward host lookup failed: Unknown host
```

**Comment by Didayolo** [comment]
Login works again

**Comment by Didayolo** [comment]
The issue should be solved now. Please re-open it if you are facing the issue again.

**Comment by crockwell** [comment]
Amazing, it works now, thanks so much!
