### ISSUE TITLE
SemanticKITTI: Moving Object Segmentation- IOError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by ccyyu2** [codalab/codalab-competitions#3490]
Error:
Traceback (most recent call last):
  File "/worker/worker.py", line 323, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 180, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 180, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 140, in get_bundle
    z.extractall(bundle_path)
  File "/usr/lib/python2.7/zipfile.py", line 1063, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/lib/python2.7/zipfile.py", line 1051, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/lib/python2.7/zipfile.py", line 1107, in _extract_member
    shutil.copyfileobj(source, target)
  File "/usr/lib/python2.7/shutil.py", line 66, in copyfileobj
    fdst.write(buf)
IOError: [Errno 28] No space left on device

**Comment by Didayolo** [comment]
Thank you for reporting this problem. I close this issue because it is already reported here #3488.

We are going to resolve the bug in a short time. Sorry for the inconvenience.
