### ISSUE TITLE
testing error

### ISSUE THREAD

**Issue by zwq456** [codalab/codalab-competitions#3529]
When I submit my json file to 'The 3nd Large-scale Video Object Segmentation Challenge - Track 2: Video Instance Segmentation', I encounter the following error:

```
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  Running command git clone -q https://github.com/youtubevos/cocoapi.git /tmp/pip-install-2c2glxke/pycocotools
  fatal: unable to access 'https://github.com/youtubevos/cocoapi.git/': Failed to connect to github.com port 443: Connection timed out
ERROR: Command "git clone -q https://github.com/youtubevos/cocoapi.git /tmp/pip-install-2c2glxke/pycocotools" failed with error code 128 in None
Traceback (most recent call last):
  File "/tmp/codalab/tmpGx9DyP/run/program/evaluate.py", line 8, in <module>
    install("git+https://github.com/youtubevos/cocoapi.git#\"egg=pycocotools&subdirectory=PythonAPI\"")
  File "/tmp/codalab/tmpGx9DyP/run/program/evaluate.py", line 6, in install
    subprocess.check_call("pip install " + package, shell=True)
  File "/opt/conda/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'pip install git+https://github.com/youtubevos/cocoapi.git#"egg=pycocotools&subdirectory=PythonAPI"' returned non-zero exit status 1.
```
I have tried many times, and the results are always like this.

**Comment by Didayolo** [comment]
Are you a competition participant or the organizer of the challenge?

- If you are participant, please report the problem to the organizers and close this issue
- If you are organizers, try to check what's happening inside your ingestion program (`evaluate.py`). Looks like a pip install is failing, maybe the repository pointed is not working. Custom docker images can be used to include packages instead of using pip install inside the ingestion program.
