### ISSUE TITLE
Failed submissions

### ISSUE THREAD

**Issue by hjin200** [codalab/codalab-competitions#3537]
Starting from last night (October 31, 2024), my submissions failed. It was all working before. So I don't think this is browser related. Here are details of the information.
1. I am using Chrome.  
2. URL of the problem: https://codalab.lisn.upsaclay.fr/competitions/7384#participate-submit_results
3. After I submitted the .zip file, the status turned to "Submitted", and then "Running". After that, the status is changed to "Failed" with the following error message returned from your system:
"/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/tmp/codalab/tmpJNweKd/run/program/run.py", line 120, in 
    cocoDt=cocoGt.loadRes(resFile)
  File "/opt/conda/lib/python2.7/site-packages/pycocotools/coco.py", line 317, in loadRes
    'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set"

**Comment by hjin200** [comment]
I uploaded results on validation dataset instead of test dataset. Issue can be closed.

**Comment by hjin200** [comment]
I uploaded results on validation dataset instead of test dataset. Issue can be closed.
