### ISSUE TITLE
Potential bug making submissions - Connection reset by peer

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#915]
```
Traceback (most recent call last):
  File "/home/azureuser/codalab/codalab/codalabtools/compute/worker.py", line 395, in run
    _send_update(queue, task_id, 'finished')
  File "/home/azureuser/codalab/codalab/codalabtools/compute/worker.py", line 160, in _send_update
    queue.send_message(body)
  File "/home/azureuser/codalab/codalab/codalabtools/azure_extensions.py", line 81, in send_message
    self._try_request(op, fail=fail)
  File "/home/azureuser/codalab/codalab/codalabtools/azure_extensions.py", line 57, in _try_request
    return fn()
  File "/home/azureuser/codalab/codalab/codalabtools/azure_extensions.py", line 79, in 
    op = lambda: self.service.send_queue_message(self.name, Message(body))
  File "/home/azureuser/venv/local/lib/python2.7/site-packages/azure/servicebus/servicebusservice.py", line 643, in send_queue_message
    response = self._perform_request(request)
  File "/home/azureuser/venv/local/lib/python2.7/site-packages/azure/servicebus/servicebusservice.py", line 782, in _perform_request
    resp = self._filter(request)
  File "/home/azureuser/venv/local/lib/python2.7/site-packages/azure/http/httpclient.py", line 147, in perform_request
    resp = connection.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
error: [Errno 104] Connection reset by peer
```

Happens sometimes when making a submission

**Comment by FlavioAlexander** [comment]
This problem was caused by port used on worksheets site. Since we have competitions and worksheets on different servers, I haven't seen the error anymore.
